--Critter Emote

--The emote table was rewritten at version 1.5

--Some important Emote tables
---Random
---Target

--Organized via
---Emote,default/Category/PetName,emotes
CritterEmote_ResponseDb = {

ABSENT = {
	default = {
		"blinks at you.",
	},
  ooze = { 
    "sits there unchanged.",
  },
  inanimate = {
    "sits there unchanged.",
  },
  ["Deathy"] = {
   "starts a little fire.",
  },
  ["Lil' Deathwing"] = {
   "starts a little fire.",
  },
  ["Lil' K.T."] = {
    "is used to dealing with absent minded zombies.",
  }
 
},
AGREE = {
	default = {
		"nods.",
	},
  ["Lil' K.T."] = {
    "knew you would.",
    ["Lil' Ragnaros"] = {   "commends you."},
  }
},
AMAZE = {
	default = {
		"smiles brightly.",
	},
	ooze = { 
    "explodes into smaller oozes and reforms.",
  },
	inanimate = {
    "does even more and can be yours for only 3 easy payments of 20 gold.",
  },
    ["Deathy"] = {
   "is the ultimate murloc-deathwing crossbreed.",
  },
    ["Gregarious Grell"] = { "does a frontflip", 
  },
   
    ["Lil' Deathwing"] = {
   "is amazing because he's the spawn of deathwing.",
  },
	["Lil' K.T."] = { 
    "is amazing and once was the most powerful Kirin Tor mage.",
    ["Lil' Ragnaros"] = {   "allowes you to bask in the glory of the firelord."},
  },
},
ANGRY = {
	default = {
		"raises its head in anger.",
	},
  ooze = { "bubbles with anger and rises in size.", },
  ["Deathy"] = {
   "blows some smoke in your face.",
  },
  ["Gregarious Grell"] = { "says, \"Can't we all just get along?\"", 
    },
  ["Lil' Deathwing"] = {
   "threatens to set your pantleg on fire.",
  },
  ["Lil' K.T."] = {
    "advises you to lower it.  You wouldn't like him when he's angry.",
  },
  ["Lil' Ragnaros"] = {   "challenges you to a duel."},
},
APOLOGIZE = {
	default = {
		"accepts your apology.",
	},
  ["Lil' K.T."] = {
    "advises you to lower it.  You wouldn't like him when he's angry.",
  }
},
APPLAUD = {
	default = {
		"takes a bow.",
	},
  ooze = {
    "bounces up and down happily.",
  },
  ["Deathy"] = {
   "does a backflip.",
  },
  ["Gregarious Grell"] = { "runs around in a circle cheering", 
    },
  ["Lil' Deathwing"] = {
   "does a little looping in the air.",
  },
  ["Lil' K.T."] = {
    "smiles narcissistically.",
  },
},
ARM = {
	default = {
		"smiles",
	},
	cat = { 
    "darts away from you.",
  },
	evil = {
    "pushes you away.",
  },
	ooze = { "clings to your arm.", },
	snake = { "curls around your arm.", },
    ["Deathy"] = {
   "is hot to the touch! Ouch! That burns!.",
  },
    ["Lil' Deathwing"] = {
   "is hot to the touch! Ouch! That burns!.",
  },
	["Lil' K.T."] = { "is cold to the touch! Ouch! Frostbolt!",
  },
},
ATTACKMYTARGET = {
	default = {
		"is scared.",
	},
	mech = { "disables safeties and prepares to defend itself.", },
	["Deathy"] = {
   "spits some lava at you.",
  },
  ["Gregarious Grell"] = { "says, \"Oooooh, sure! Send the LITTLE guy!\"", 
    },
    ["Lil' Deathwing"] = {
   "spits a fireball at you.",
  },
    ["Lil' K.T."] = { "fires a Frostbolt at you.", 
  },							  
	snake = { 
    "coils up defensively.",
	},
},
AWE = {
	default = {
		"shows off.",
  },
  ["Deathy"] = {
   "blows some smoke through his nostrils.",
  },
  ["Lil' Deathwing"] = {
   "shouts, \"I am the destroyer of worlds!\"",
  },
  ["Lil' K.T."] = {
    "strikes an intimidating pose.",
  },
},
BACKPACK = {
	default = nil,
	ooze = { "spins the stuff floating inside it like a washing machine.", },
	["Argent Squire"] = { "asks what you're looking for and if he can be of assistance.", },
	["Argent Gruntling"] = { "asks what you're looking for and if he can be of assistance.", },
	["Core Hound Pup"] = { "is afraid you are looking for a skinning knife.",
	},
},
BADFEELING = {
	default = {
		"has a bad feeling about you too!",
	},
    ["Gregarious Grell"] = { "says, \"No shi rakir no tiros kamil re lok ante refir shi rakir.\"", 
    },
  ["Lil' K.T."] = { "taunts you. Bring it!", },
},
BARK = {
	default = {
		"barks back.",
	},
    ["Deathy"] = {
   "pets you.",
  },
  ["Gregarious Grell"] = { "gives you a confused look.\"", 
    },
    ["Lil' Deathwing"] = {
   "asks you if you need to be taken for a walk?",
  },
	humanoid = { "informs you that there's no need to bark.", },
	frog = { "ribbits at you.", },
	["Lil' K.T."] = { "tells you to scream your dying breath, cur!", },
},
BASHFUL = {
	default = {
		"winks at your slyly.",
	},
    ["Deathy"] = {
   "informs you that %t is only attracted to murlocs.",
  },
    ["Lil' Deathwing"] = {
   "informs you %t doesn't swing that way.",
  },
  ["Lil' K.T."] = { "tells you that your curiousity will be the death of you.",
  },
},
BECKON = {
	default = {
		"comes closer.",
	},
	cat = { "runs off, bored with you.", },
	["Ethereal Soul-Trader"] = { "says, \"Got something that might interest you, stranger.\"",
	},
    ["Deathy"] = {
   "hops towards you",
  },
  ["Gregarious Grell"] = { "says, \"Allright, I'm coming.\"", 
    },
    ["Lil' Deathwing"] = {
   "flies closer.",
  },
	["Lil' K.T."] = { "stares you down disdainfully.",
	},
},
BEG = {
	default = nil,
	evil = { "back hands you.",
	},
	["Ethereal Soul-Trader"] = { "is not affected by mind tricks, only money.",
	},
    ["Deathy"] = {
   "tells you he doesn't do charity.",
  },
    ["Lil' Deathwing"] = {
   "thinks you shouldn't be begging with the amount of gold you have.",
  },
	["Lil' K.T."] = {	"tells you to pray for mercy.",
    ["Lil' Ragnaros"] = {   "promises to spare your life if you carry %t around."},
  },
},
BITE = {
	default = {
		"bites back. Rawr.",
	},
	cat = { "hisses and scratches back.", },
	dino = { "tries to bite back at you, but misses. You could lose a finger that way!.", },
	humanoid = {  "pushes you away. You're not a zombie or vampire are you?!",
	},
	mech = { "is made of metal. Ouch!", },
	ooze = { "is filthy! You should wash your mouth thoroughly and call poison control.", },
    ["Deathy"] = {
   "shoots a fireball at your feet while telling you to dance!",
  },
  ["Gregarious Grell"] = { "shoots a Firebolt at you.\"", 
    },
    ["Lil' Deathwing"] = {
   "shoots a fireball at your feet while telling you to dance!",
  },
	["Lil' K.T."] = { "sends undead minions to eat your brains. Brains!",
    ["Lil' Ragnaros"] = {   "tells you that 3 of your teeth just melted."},
  }, 
},
BLAME = {
	default = {
		"cries.",
	},
	cat = { "doesn't seem to care and strolls away, tail raised and swaying mockingly.", },
    ["Deathy"] = {
   "appologises for your many Dragon Soul wipes",
  },
  ["Gregarious Grell"] = { "says, \"I was only following orders!\"", 
    },
    ["Lil' Deathwing"] = {
   "appologises for your many Dragon Soul wipes",
  },
	["Lil' K.T."] = { "informs you the failure is yours!",},
    ["Lil' Ragnaros"] = {   "blames Malfurion Stormrage."},
},
BLANK = {
	default = {
		"stares back at you. Staring contest!",
	},
    ["Deathy"] = {
   "stares at you with fiery eyes.",
  },
    ["Lil' Deathwing"] = {
   "stares at you with fiery eyes.",
  },
  ["Lil' K.T."] = {  "stares at you with ice cold eyes.",},
},
BLEED = {
	default = nil,
	evil = { "is not squimish.",},
	humanoid = { "looks for some Heavy Frostweave bandages.", },
    ["Deathy"] = {
   "asks if you want %t to cauterize the wound?",
  },
    ["Lil' Deathwing"] = {
   "asks if you want %t to cauterize the wound?",
  },
  ["Lil' Ragnaros"] = {   "asks if you want %t to cauterize the wound?"},
},
BLINK = {
	default = {
		"blinks back at you.",
	},
},
BLUSH = {
	default = {
		"smiles at you.",
	},
    ["Deathy"] = {
   "tells you murlocs tend to have that effect on pet owners.",
  },
    ["Lil' Deathwing"] = {
   "informs you that %t would rather focus on world domination then romance.",
  },
  ["Lil' K.T."] = { "knows he\'s impressive but doesn't like you in that way.",},
  ["Lil' Ragnaros"] = {   "is glowing a little brighter."},
},
BOGGLE = {
	default = nil,
	evil = {  "makes a scary face, Boo!", },
},
BONK = {
	default = {
		"says \"Ow!\"",
	},
	mech = { "makes strange whirring noises. You broke it! Hope it's under warranty.", },
	murloc = { "looks irked and says, \"Mrrwlwlwlwrwl.\"", },
	["flying insect"] = { "flies erratically.", },
},
BORED = {
	default = {
		"frowns.",
	},
	ooze = { "moves sluggishly.", },
    ["Deathy"] = {
   "sets a nearby object on fire!",
  },
  ["Gregarious Grell"] = { "says, \"My last master died of boredom.\"", 
    },
    ["Lil' Deathwing"] = {
   "asks you if you would like to raid Dragon Soul?",
  },
	["Lil' K.T."] = { "is bored with you and your constant raids against his fortress.", },
    ["Lil' Ragnaros"] = {   "asks if you want to raid Naxxramas."},
},
BOUNCE = {
	default = {
		"is amused.",
	},
	beast = { "jumps up into the air playfully.", },
	ooze = { "bounces up and down with you.", },
	["Lil' K.T."] = { "doesn't like this foolishness.",},
},
BOW = {
	default = {
		"bows at you.",
	},
    ["Deathy"] = {
   "praises you for acknowledging %t's superiority.",
  },
  ["Gregarious Grell"] = { "looks at you confused.", 
    },
    ["Lil' Deathwing"] = {
   "praises you for acknowledging %t's superiority.",
  },
  ["Lil' K.T."] = {  "acknowledges your presence, but barely.",},
  ["Lil' Ragnaros"] = {   "praises you for acknowledging %t's superiority."},
},
BRANDISH = {
	default = {
		"watches you guardedly.",
	},
  ooze = {  "brandishes a femur bone at you.", },
},
BREATH = {
	default = {
		"takes a deep breath.",
	},
	mech = { "starts to emanate smoke. Oh no! It's on fire.", },
	["Onyxian Whelpling"] = { "summons more whelps!",
	},
    ["Deathy"] = {
   "breathes out a fireball!",
  },
    ["Lil' Deathwing"] = {
   "breathes out a giant flame!",
  },
	["Lil' K.T."] = { "can't remember the last time he took a breath.", },
    ["Lil' Ragnaros"] = {   "blows out some smoke."},
},
BURP = {
	default = {
		"thinks you're disgusting.",
	},
	dragon = { "burps a puff of fire.",
	}, 
	ooze = { "burps out a wishbone.",
	},
	murloc = { "lets out a loud belch.",
	},
	cat = {
		"coughs up a hairball.",
	},
	snake = {
		"coughs up a small critter.",
	},
    ["Deathy"] = {
   "burps out a puff of fire.",
    },
},
BYE = {
	default = {
		"waves good bye.",
	},
  mech = { "shuts down.", },
  ["Gregarious Grell"] = { "says, \"You know, we've had a lot of fun together, its been really special, but I think it's time I should start seeing other masters. Just a little on the side. No no no its not you, its not you, its me. I just need my space.\"", 
    },
},
CACKLE = {
	default = {
		"cackles manically with you.",
	},
	cat = {
		"looks manically with you.",
	},
	snake = {
		"looks manically with you.",
	},
},
CALM = {
	default = {
		"is calmed.",
	},
},
CHALLENGE = {
	default = {
		"has defeated you in a duel!.",
	},
    ["Gregarious Grell"] = { "doesn't want to fight its master.", 
    },
    ["Lil' Ragnaros"] = {   "shouts, \"Fall to your knees, mortal! This ends now!\""},
},
CHARGE = {
	default = nil,
  ["Deathy"] = {
   "shouts, \" For Deathwing!\"",
  },
  ["Gregarious Grell"] = { "says, \"Make yourself useful and help me out on this one!\"", 
    },
  ["Lil' Deathwing"] = {
   "shouts, \" For Deathwing!\"",
  },
  ["Lil' K.T."] = { "shouts, \"In the Lich King's name!\"", },
  ["Lil' Ragnaros"] = {   "shouts, \"enough! I will finish this!\""},
},
CHARM = {
	default = {
		"smiles at you.",
	},
  evil = { "feels pretty smug right about now.", },
},
CHEER = {
	default = {
		"raises hands in air victoriously.",
	},
	bird = { "fans out wings and lets out a victory screech.", },
	crab = { "raises claws in air.", },		
	mech = { "fires out a mini celebration firework.", },		
},
CHICKEN = {
	default = {
		"is ready! Bring it!",
	},
	beast = { "is confused. You're not a chicken.", },
	bird = { "cocks its head to on side and stares at you.", },
	cat = { "comes up to you inquisitively.", },
	insect = { "scurries away to hide.", },
	["Ancona Chicken"] = { "clucks back.", },
	["Westfall Chicken"] = { "expects Special Chicken Feed.", },
    ["Lil' Ragnaros"] = {   "asks you if you like friend chicken."},
},
CHUCKLE = {
	default = {
		"wants to know what's so funny?!",
	},
	cat = {
		"meow?!",
	},
	snake = {
		"hisses?!",
	},
},
CHUG = {
	default = {
		"shakes its head. No! Not going to happen.",
	},
},
CLAP = {
	default = {
		"takes a bow.",
	},
	cat = {
		"purrs.",
	},
	snake = {
		"hisses.",
	},
  ["Lil' K.T."] = { "nods and raises his hand for silence.",},
  ["Lil' Ragnaros"] = {   "takes a small bow."},
},
COLD = {
	default = { "says \"Winter is Coming!\""},
	beast = { "cuddles close to you to warm you.", },	
	snake = { "looks for a warm rock to hide under.", },
    ["Deathy"] = {
   "breathes some fire at your pantleg to warm you up",
  },
    ["Lil' Deathwing"] = {
   "breathes some fire at your pantleg to warm you up",
  },
  ["Lil' K.T."] = { "lets you know he's always cold. Ice ice baby.",},
  ["Lil' Ragnaros"] = {   "sets your pantleg on fire. Hot!"},
},
COMFORT = {
	default = {
		"is comforted.",
	},
},
COMMEND = {
	default = {
		"jumps up in happiness.",
	},
    ["Gregarious Grell"] = { "shouts, \"%t did good!\"", 
    },
  ["Lil' K.T."] = {  "smiles to himself.", },
  ["Lil' Ragnaros"] = {   "thanks you for your praise."},
},
CONFUSED = {
	default = {
		"shrugs.",
	},
	cat = {
		"looks confused.",
	},
	snake = {
		"looks confused.",
	},
	mech =  { "searches database for correct response.", },
},
CONGRATULATE = {
	default = {
		"thanks you.",
	},
	cat = {
		"looks happy! Meow.",
	},
	snake = {
		"looks happy! hiss.",
	},
  evil = { "would like to thank all the little people he stepped on along the way.", },
},
COUGH = {
	default = {
		"doesn't want to get sick!",
	},
	cat = {
		"coughs up a hairball.",
	},
	snake = {
		"coughs up a small critter.",
	},
	mech = { "does not recognize that voice command.",
	},
	ooze = { "coughs up a hairball. What's that doing there.", },
	["Lil' K.T."] = { "laughs at how fragile you mortals are.", },
    ["Lil' Ragnaros"] = {   "tells you to keep smoking."},
},
COVEREARS = {
	default = {
		"can't hear!",
	},
	evil = {  "wants you to remove your hands immediately.",},
},
COWER = {
	default = {
		"roars.",
	},
	ooze = { "flattens itself and shakes with fear.", },
    ["Deathy"] = {
   "cower in fear for the mighty Deathwing!",
  },
    ["Lil' Deathwing"] = {
   "cower in fear for the mighty Deathwing!",
  },
	["Lil' K.T."] = { "cower in fear of the might of the Scourge!", },
    ["Lil' Ragnaros"] = {   "cower before Sulfuras!"},
},
CRACK = {
	default = {
		"stares at you menacingly.",
	},
},
CRINGE = {
	default = {
		"feels unloved.",
	},
	evil = { "does the Thriller dance.", },
},
CROSSARMS = {
	default = {
		"turns its head away from you. Hmph!",
	},
},
CRY = {
	default = {
		"tries to comfort you.",
	},
	cat = {
		"snuggles you.",
	},
	snake = {
		"snuggles you.",
	},
  beast = {  "licks you and tries to comfort you.", },
	["Lil' K.T."] = { "feeds on your tears.", },
    ["Lil' Ragnaros"] = {   "accepts your appology."},
},
CUDDLE = {
	default = {
		"cuddles back.",
	},
	cat = {
		"cuddles back around your legs.",
	},
	snake = {
		"slides back around your legs.",
	},
	murloc = { "is scaley and kind of slimey.  Maybe this wasn't such a good idea.", },
    ["Lil' Deathwing"] = {
   "accidently burns the front of your armor",
  },
	["Lil' K.T."] = {  "knows you're a fan, but please keep your mortal hands off!",},
    ["Lil' Ragnaros"] = {   "burns off the front of your armor."},
},
CURIOUS = {
	default = nil,
    ["Deathy"] = {
   "informs you murlocs eat seaweed for breakfast",
  },
  ["Gregarious Grell"] = { "informs you that imps have very low hitpoints.\"", 
    },
    ["Lil' Deathwing"] = {
   "informs you that dragons eat insects for breakfast",
  },
  ["Lil' K.T."] = {  "tells you that your curiosity will be the death of you.",},
  ["Lil' Ragnaros"] = {   "tells you that your curiosity will be the death of you"},
},
CURTSEY = {
	default = {
		"bows before you politely.",
	},
	cat = {
		"purrs.",
	},
	snake = {
		"hisses.",
	},
  ["Lil' K.T."] = { "acknowledges your presence, but barely.", },
},
Clean = {
	cat = {
		"purrs.",
	},
	snake = {
		"hisses.",
	},
},
DANCE = {
	default = {
		"dances with you",
	},
	snake = {
		"slides around to the beat.",
	},
	ooze = {  "weaves around your legs as you dance.", },
	["Teldrassil Sproutling"] = { "does the twist.", },
    ["Deathy"] = {
   "busts out some moves to disco ",
  },
  ["Gregarious Grell"] = { "does the Thriller", 
    },
    ["Lil' Deathwing"] = {
   "busts out some moves to hardcore.",
  },
	["Lil' K.T."] = { "does the Pop and Lock dance.", },
    ["Lil' Ragnaros"] = {   "does the macarena and complains about not having any legs."},
},
DING = {
	default = nil,
},
DISAGREE = {
	default = {
		"thinks we should agree to disagree.",
	},
	cat = {
		"looks at you confused.",
	},
	snake = {
		"looks at you confused.",
	},
	evil = { "thinks you have the right to your WRONG opinion.", },
},
DOUBT = {
	default = {
		"feels insecure.",
	},
	["Lil' K.T."] = {  "is the mighty K.T.. How dare you doubt him!", },
    ["Lil' Ragnaros"] = {   "wonders about making a comeback."},
},
DRINK = {
	default = {
		"cheers!",
    ["Deathy"] = {  "grabs a Fiery Festival Brew and enjoys it.", },
	},
},
DROOL = {
	default = {
        "wonders if you are mentally retarded.",
    },    
	ooze = { "drips slime.", },
	["Lil' K.T."] = { "once knew a ghoul who drooled. I called him Drooly.", },
    ["Lil' Ragnaros"] = {   "drools some lava onto you. Ouch!"},
},
DUCK = {
	default = {
		"shields you.",
	},
	evil = { "side steps and leaves you vulnerable.", },
},
EAT = {
	default = {
		"is hungry too!",
	},
	snake = {
		"is hungry too! Let's find some critters.",
	},
	dino = { "hopes you brought meat.", },
	mech = { "initiates regeneration mode.", },
    ["Deathy"] = { "hopes you forget to wait for you food buff.", },
    ["Gregarious Grell"] = { "says, \"Don't forget our foodbuff!\"", 
    },
    ["Lil' Deathwing"] = { "hopes you forget to wait for you food buff.", },
	["Lil' K.T."] = { "hopes you forget to wait for you food buff.", },
    ["Lil' Ragnaros"] = {   "asks, \"Would you like some barbeque?\""},
	["Warbot"] = { "has a secret stash of Mountain Dew.",},
},
ENCOURAGE = {
	default = {
		"is encouraged.",
	},
},
ENEMY = {
	default = {
		"tenses up.",
	},
    ["Gregarious Grell"] = { "says, \"What? You mean you can't kill this one by yourself?\"", 
    },
  ["Lil' K.T."] = {  "scowls about intruders daring to invade his sanctum.", },
  ["Lil' Ragnaros"] = {   "complains about raiders in the Firelands."},
},
EYE = {
	default = nil,
  evil = {  "strikes a rather fiendish looking pose.", },
},
EYEBROW = {
	default = nil,
},
FACEPALM = {
	default = {
		"hides in shame.",
	},
  ["Deathy"] = { "informs you someone starting singing what is love.", },
  ["Lil' Deathwing"] = { "asks you if someone mentioned Chuck Norris.", },  
  ["Lil' K.T."] = { "checks to see if his robes are on backwards again. They aren't backwards, are they?.", },
  ["Lil' Ragnaros"] = {   "blaims you for %t's mistake."},
},
FAINT = {
	default = nil,
    ["Lil' Deathwing"] = { "tries to barbeque your corpse.", },
    ["Lil' Ragnaros"] = {   "takes credit for slaying you."},
},
FART = {
	default = {
		"is disgusted!",
	},
	beast = { "tries to shield its nose.", },
	ooze = {  "explodes and then reforms.", },
    ["Deathy"] = { "tells you not even murlocs smell that bad.", },
    ["Lil' Deathwing"] = { "asks if you had onions for breakfast.", },
	["Lil' K.T."] = { "is glad his sense of smell died with his mortal body.",},
    ["Lil' Ragnaros"] = {   "holds a light to your fart. Flamethrower!"},
},
FIDGET = {
	default = {
		"tries to hurry.",
	},
    ["Gregarious Grell"] = { "runs around fidgeting.", 
    },
  ["Lil' K.T."] = { "has to make sure his phylactery is safe. The precious...",},
},
FLEE = {
	default = nil,
	bird = { "flies away.", },
    ["Deathy"] = { "is immune to fear effects.", },
    ["Gregarious Grell"] = { "says, \"Ahh! Okay, okay, okay, okay, okay, okay!\"", 
    },
    ["Lil' Deathwing"] = { "is immune to fear effects.", },
	["Lil' K.T."] = { "is immune to fear effects.", },
    ["Lil' Ragnaros"] = {   "refuses."},
},
FLEX = {
	default = {
		"is impressed",
	},
  ["Deathy"] = { "reminds you that you are puny in comparison to Deathwing.", },
  ["Gregarious Grell"] = { "says, \"Master is looking powerfull today.\"", 
    },
  ["Lil' Deathwing"] = { "reminds you that you are puny in comparison to Deathwing.", },
  ["Lil' K.T."] = { "flexes his muscles. Oh wait! Nothing but bone.",},
  ["Lil' Ragnaros"] = {   "informs you that flesh is weak."},
},
FLIRT = {
	default = {
		"blushes at you.",
	},
  ["Deathy"] = { "tells you that he has full heroic gear and an expensive mount.", },  
  ["Lil' Deathwing"] = { "tells you that he has full heroic gear and an expensive mount.", },  
  ["Lil' K.T."] = {  "tells you that he has legions of tireless servants and an expensive mount.",},
  ["Lil' Ragnaros"] = {   "winks and asks if you would like a Firelands boost."},
},
FLOP = {
	default = {
		"facepalms.",
	},
	beast = { "flops around with you thinking it's a game.",
	},
	ooze = { "flops over like a slinky.", },
    ["Gregarious Grell"] = { "shouts, \"Noooo, master is down, we need a healer!\"", 
    },
	["Lil' K.T."] = { "flee for only death awaits you, helpless mortal!",},
    ["Lil' Ragnaros"] = {   "flee for only death awaits you, puny insect!"},
},
FOLLOW = {
	default = {
		"is already following that target!",
	},
},
FROWN = {
	default = {
		"feels ashamed.",
	},
    ["Gregarious Grell"] = { "explains to you that he is a better version then the standard warlock imp.", 
    },
	["Lil' K.T."] = { "is the best investment ever. How can you be disappointed?",},
    ["Lil' Ragnaros"] = {   "informs you that besides being a pet, %t also makes a great cooking fire."},
},
GASP = {
	default = nil,
},
GAZE = {
	default = {
		"looks back at you.",
	},
},
GIGGLE = {
	default = nil,
},
GLARE = {
	default = {
		"hides.",
	},
  evil = { "glares back. So fierce!", },
},
GLOAT = {
	default = nil,
  ["Deathy"] = { "You may have won this battle, I give you that. But hear this, and hear it well. I have seen you", },
  ["Gregarious Grell"] = { "says, \"Minion knows master is great.\"", 
    },
  ["Lil' Deathwing"] = { "You may have won this battle, I give you that. But hear this, and hear it well. I have seen you", },  
  ["Lil' K.T."] = {  "scoffs, \"A minor setback.\"",},
  ["Lil' Ragnaros"] = {   "shouts, \"you have come too soon!\""},
},
GLOWER = {
	default = {
		"hides.",
	},
  ["Lil' K.T."] = {  "rolls his eyes at you.",},
},
GO = {
	default = {
		"leaves feeling unwanted.",
	},
    ["Gregarious Grell"] = { "says, \"Don't call on me, I'll call on you.\"", 
    },
    ["Lil' K.T."] = { "has other places to be anyways.",},
    ["Lil' Ragnaros"] = {   "retreats into the lava."},
},
GOING = {
	default = {
		"will tag along.",
	},
},
GOLFCLAP = {
	default = {
		"doesn't appreciate the sarcasm.",
	},
},
GREET = {
	default = {
		"waves back.",
	},
	cat = {
		"looks at you. Meow?",
	},
	snake = {
		"looks at you. hiss?",
	},
	bird = { "perches on your shoulder and chirps a greeting.", },
	["flying insect"] = { "lands on your shoulder.", },
	["Lil' K.T."] = { "doesn't seem interested.", },
    ["Lil' Ragnaros"] = {   "shoo's you"},
},
GRIN = {
	default = nil,
	evil = { "grins at you with a menacing display of teeth.", },
},
GROAN = {
	default = nil,
},
GROVEL = {
	default = nil,
  ["Gregarious Grell"] = { "has waited a long time to be the master.", 
    },  
  ["Lil' K.T."] = {  "says, \"Come child, the Lich King has plans for you.\"",},
  ["Lil' Ragnaros"] = {   "says, \A new servent has arisen.\""},
},
GROWL = {
	default = nil,
	beast = { "growls back.",},
	dino = {  "roars at you.",},
},
GUFFAW = {
	default = nil,
  ["Lil' K.T."] = {  "glares at you. \"My robes have a higher gear score than your raggy ensemble.\"",},
  ["Lil' Ragnaros"] = {   "hisses at you. \"Sulfuras has a higher gear score then all your characters combined.\""},
},
HAIL = {
	default = {
		"hails back.",
	},
	cat = {
		"looks at you. Meow?",
	},
	snake = {
		"looks at you. hiss?",
	},
},
HAPPY = {
	default = {
		"feels warm and fuzzy inside.",
	},
},
HEADACHE = {
	default = nil,
},
HEALME = {
	default = nil,
  humanoid = { "gives you an extra healing potion.", },
    ["Gregarious Grell"] = { "reminds you imps don't do healing.", 
    }, 
	["Lil' K.T."] = { "doesn't do healing, but will gladly raise you after you're dead.",},
    ["Lil' Ragnaros"] = {   "asks if you want to be cauterized."},
},
HELLO = {
	default = {
		"waves back.",
	},
	cat = {
		"looks at you. Meow?",
	},
	snake = {
		"looks at you. hiss?",
	},
	bird = { "chirps a hello.", },
    ["Gregarious Grell"] = { "says, \"Greetings master.\"", 
    },
	["Lil' K.T."] = { "says, \"You address me, mortal?\"",},
    ["Lil' Ragnaros"] = {   "says, \"Your pathetic mortal world will burn with my vengeance!\""},
},
HELPME = {
	default = nil,
},
HICCUP = {
	default = nil,
},
HIGHFIVE = {
	default = nil,
	humanoid = { "high fives back.", },
	snake = { "slaps its tail against your hand.", },
    ["Gregarious Grell"] = { "highfives back while cheering.", 
    },
	["Lil' K.T."] = { "high fives back. Yuh, we bad!", },
    ["Lil' Ragnaros"] = {   "cheers. By fire be purged!"},
},
HISS = {
	default = nil,
	snake = { "hisses back at you.", },
    ["Gregarious Grell"] = { "says, \"Reminds you that your on the same team.\"", 
    },
	["Lil' K.T."] = { "hopes this doesn't turn into a hissy fit.", },
    ["Lil' Ragnaros"] = {   "warns you."},
},
HOLDHAND = {
	default = 	nil,
	bird = {  "offers a wing for you to hold.", },
	snake = {  "doesn't have hands!",},
	["Lil' K.T."] = { "isn't a scrub and doesn't need his hand held.",},
    ["Lil' Ragnaros"] = {   "burns you. Ouch!"},
},
HUG = {
	default =	nil,
	beast = { "hugs back.", },
	humanoid = { "returns the hug.", },
    ["Gregarious Grell"] = { "says, \"%t loves the master too!\"", 
    },
	["Lil' K.T."] = { "thinks this is awkward.",},
    ["Lil' Ragnaros"] = {   "makes it clear that this does not make up for your last raid."},
},
HUNGRY = {
	default = {
		"shakes its head.",
	},
	bird = { "offers an extra cracker held in its beak.", },
	evil = { "doesn't want to share with you.",},
  mech = { "has an extra battery to offer.", },
	snake = { "spits out a whole egg. Lucky it wasn't a rat.", },
	["Warbot"] = { "thinks you should get some Mountain Dew.",},
	["Lil' K.T."] = { "hungers for the suffering of others.",},
    ["Lil' Ragnaros"] = {   "wants to watch the world burn."},
},
HURRY = {
	default =nil,
	mech = { "optimizes its current task.", },
    ["Gregarious Grell"] = { "says, \"Alright, I'm on it! Stop yelling!\"", 
    },
    ["Lil' K.T."] = { "tells you to respect your elders and not give him sass.",},
    ["Lil' Ragnaros"] = {   "tells you he doesn't have legs...yet."},
},
IDEA = {
	default = nil,
  ["Gregarious Grell"] = { "asks you to explain in detail.", 
    },  
  ["Lil' K.T."] = { "thinks your mortal ideas are small and lack insight.",},
  ["Lil' Ragnaros"] = {   "explains to you that your idea lacks fire."},
},
INCOMING = {
	default = 	nil,
  ["Gregarious Grell"] = { "says, \"THIS WAS NOT IN MY CONTRACT!\"", 
    },  
  ["Lil' K.T."] = { "rolls with an army of Undead as well. Death Knights eat your hearts out.",},
},
INSULT = {
	default = nil,
	bird = { "pecks at you with its beak and screeches at you.", },
	ooze = { "spits a bone at you.", },
    ["Gregarious Grell"] = { "asks you if you feel big now.", 
    },
	["Lil' K.T."] = { "threatens to freeze the blood in your veins.", },
    ["Lil' Ragnaros"] = {   "says, \Arise, servants of fire! Consume their flesh!\""},
},
INTRODUCE = {
	default = 	nil,
	bird = { "squawks a greeting.", },
	mech = { "scans you and saves a profile.", },
    ["Gregarious Grell"] = { "introduces himself.", 
    },
	["Lil' K.T."] = { "asks, \"Do you know who I am?\"",},
    ["Lil' Ragnaros"] = {   "says, \"I need no introduction, insect!\""},
},
JEALOUS = {
	default = nil,
  cat = { "holds its head up smugly.", },
    ["Gregarious Grell"] = { "knows he has awsome earrings.", 
    },
	["Lil' K.T."] = { "is naturally the envy of all of Azeroth and then some.",},
    ["Lil' Ragnaros"] = {   "firmy holds onto Sulfuras."},
},
JK = {
	default = nil,
  ["Lil' K.T."] = { "lets you know that he wasn't about having you slain in your sleep.",},
},
JOKE = {
	default = {
		"smiles.",
	},
  ["Gregarious Grell"] = { "tells a joke, \"Why should you never go to dinner with a Rogue? He'll vanish when the bill comes!\"", 
    },  
  ["Lil' K.T."] = { "tells a joke, \"Three mounted knights enter Naxxramas and ask me for a place to stay for the night. I politely decline and tell them, \'I'm already housing Four Horsemen!\' Ha!\"",},
  ["Lil' Ragnaros"] = {   "reminds you of your first trip to The Firelands."},
},
KISS = {
	default = {
		"catches it.",
	},
	cat = {
		"purrs.",
	},
	snake = {
		"hisses.",
	},
	frog = { "wonders if a kiss on the lips will make it human.", },
	["Lil' K.T."] = { "doesn't like this.",},
    ["Lil' Ragnaros"] = {   "doesn't swing that way."},
},
KNEEL = {
	default =nil,
	beast = { "comes closer and licks your face.",
	},
	cat = { "inches closer to see if you've brought food.", },
    ["Gregarious Grell"] = { "wonders how life would be with you as %t's companion.", 
    },
	["Lil' K.T."] = { "nods in approval as you answer the call of the Lich King.",},
    ["Lil' Ragnaros"] = {   "explains that worshippers will be granted power."},
},
LAUGH = {
	default = {
		"doesn't like being laughed at.",
	},
	mech = { "lets out a lifeless mechanical laugh.", },
},
LAYDOWN = {
	default =	nil,
	beast = { "curls up on your lap.",},
    ["Lil' K.T."] = { "likes where this is going.",},
    ["Lil' Ragnaros"] = {   "accepts your surrender."},
},
LICK = {
	default = nil,
	beast = { "nuzzles you.", },
	cat = {  "licks back and purrs.", },
	crab = { "tastes fishy.", },
	["flying insect"] = { "tastes like bug. Did you just lick a bug?!", },
	humanoid = { "looks at you strangely.", },
	insect = { "tastes like bug. Did you just lick a bug?!", },
	mech = {"tastes like metal.",
	},
    ["Gregarious Grell"] = { "tells you %t doesn't serve you in that way.\"", 
    },
	["Lil' K.T."] = { "tastes like a blueberry popsicle.",
    ["Lil' Ragnaros"] = {   "tastes like a burned pizza and burns your tongue. Ouch!"},
	},		
},
LISTEN = {
	default = nil,
	inanimate = { "is inanimate.  You might be crazy! Consult your nearest healer.", },
	mech = {  "sounds like it is operating nominally.", },
	ooze = {  "makes disgusting bubbling noises.", },
},
LOOK = {
	default =nil,
},
LOST = {
	default = nil,
	beast = { "goes ahead to blaze a trail and find the way.", },
  cat = { "is too cool to be lost and leaves you to your own devices.", },
	mech = { "activates its GPS unit and homing beacon.", },
  ["Gregarious Grell"] = { "reminds you to open your map.\"", 
    },  
  ["Lil' K.T."] = { "offers you a brochure for the Cult of the Damned. Answers lie within.",},
  ["Lil' Ragnaros"] = {   "asks you to start a small fire, just for signaling offcourse."},
},
LOVE = {
	default = {
		"feels loved.",
	},
	humanoid = { "likes you, but doesn't like you like you.", },				
	ooze = { "turns into a little heart shape.", },
  ["Gregarious Grell"] = { "shouts, \"%t loves the master too!\"", 
    },  
  ["Lil' K.T."] = { "has no time for love while in servitude of the glorious Lich King.",},
  ["Lil' Ragnaros"] = {   "is too focused on his carreer for love."},
},
LUCK = {
	default = nil,
  ["Lil' K.T."] = { "doesn't need luck when he has magic, such powerful magic.",},
},
MAP = {
	default = nil,
},
MASSAGE = {
	default = nil,
	humanoid = { "thanks you for the wonderful massage.", },
	ooze = { "is kneaded like dough. You're not going to bake it are you?!", },
    ["Gregarious Grell"] = { "enjoys this. He has a stressful job.", 
    },
	["Lil' K.T."] = { "enjoys this. He has a stressful job.",},
    ["Lil' Ragnaros"] = {   "enjoys this. He has a stressful job."},
},
MERCY = {
	default = nil,
  ["Lil' K.T."] = { "is amused by your plea for mercy.",},
  ["Lil' Ragnaros"] = {   "denies you mercy."},
},
MOAN = {
	default = nil,
    ["Gregarious Grell"] = { "grumbles indistinctly, \"I wish you were DEAD.\"", 
    },
},
MOCK = {
	default = nil,
  ["Gregarious Grell"] = { "asks, \"How did I displease the master?\"", 
    },   
  ["Lil' K.T."] = { "says, \"Mr. Bigglesworth! Slay this interloper. What?! He's been killed? WHO DID THIS?!\"",},
  ["Lil' Ragnaros"] = {   "minions of fire, purge the outsider!"},
},
MOON = {
	default = nil,
	ooze = { "shakes something at you.  Does it have a rear?", },
    ["Gregarious Grell"] = { "runs away terrified.", 
    },
	["Lil' K.T."] = { "spanks you to teach you some respect.", },
    ["Lil' Ragnaros"] = {   "fires a Magma Blast at your behind. Ouch!"},
},
MOO = {
	default = nil,
	humanoid = {  "doesn't speak cow.", },
	ooze = { "makes gurgling sounds trying to mimic you.", },
	["Lil' K.T."] = { "doesn't even know where to begin.", },
},
MOURN = {
	default = nil,
  ["Gregarious Grell"] = { "informs you that after that, you can resummon %t.", 
    },  
  ["Lil' K.T."] = { "isn't dead! Well... not dead dead. More like undead.",},
},
MUTTER = {
	default = nil,
	humanoid = { "asks you to speak up.", },
},
NERVOUS = {
	default = nil,
    ["Gregarious Grell"] = { "fidgets uncontrollably", 
    },
  ooze = {  "quivers nervously.", },
},
NO = {
	default = nil,
},
NOD = {
	default =nil,
  bird = { "bobs its head.", }
},
NOSEPICK = {
	default = nil,
	evil = { "wonders if you're going to eat it next.", },
	ooze = { "jumps onto your hand and eats it. Ew!",},
},
OBJECT = {
	default = nil,
  ["Gregarious Grell"] = { "agrees with you.", 
    },  
  ["Lil' K.T."] = {  "overrules your objection!",},
  ["Lil' Ragnaros"] = {   "reminds you that %t outranks you."},
},
OFFER = {
	default = nil,
	cat = { "hopes you brought fish.", },
	["Ethereal Soul-Trader"] = { "thinks the details need to be worked out.  Will you haggle?", 
	 },
  ["Gregarious Grell"] = { "asks if you would like to renegotiate your countract.\"", 
    },   
  ["Lil' K.T."] = { "doubts you could match the Lich King's eternal reward for servitude.",},
  ["Lil' Ragnaros"] = {   "does not make deals with insects."},
},
OOM = {
	default = nil,
},
OPENFIRE = {
	default = {
		"opens fire.",
	},
	cat = {
		"hisses.",
	},
	snake = {
		"hisses.",
	},
	humanoid = {  "opens fire.", },
	mech = { "launches rockets at the target.", },
	ooze = { "charges at the target and latches on. Nom nom nom.", },
},
PANIC = {
	default = nil,
	ooze = {  "scurries around in panic as well, leaving small puddles of goo in its wake.", },
},
PAT = {
	default = nil,
  ooze = {  "sticks momentarily to your hand and bounces up and down as it returns to equilibrium.", },
},
PEER = {
	default = {
		"hides the loot table. NO! Not going to happen.",
	},
  ["Lil' K.T."] = { "hides his loot table. NO! Not going to happen.",},
},
PET = {
	default = {
		"coos.",
	},
	bird = {  "happily flaps its wings.", },
	cat = {  "mews at you.", },
	dragon = {  "wags its tail and flaps its wings as it brushes against your hand.", },
	elephant = {  "trumpets happily.", },
	evil = {  "doesn't like this.",
	 },
	frog = {  "hops away from you.",
	 },
	humanoid = { "wants to know what you're doing exactly and looks at you strangely.", },
	ooze = {  "absorbs your hand into its gooey form.", },	
	snake = { "coils closely around your hand, enjoying the warmth.", },		
},
PINCH = {
	default = {
		"cries.",
	},
	crab = {  "snaps its pincers at you as a warning.", },
	ooze = {  "engulfs your fingers and suckles on them.",},
    ["Gregarious Grell"] = { "screams, \"THIS WAS NOT IN MY CONTRACT!\"", 
    },
	["Lil' K.T."] = {  "informs you that yes you are really in his legendary presence, but not to touch him.",},
    ["Lil' Ragnaros"] = {   "smiles while he burns your fingers."},
	["Zergling"] = { "chitters angrily." },			
},
PITY = {
	default = nil,
},
PLEAD = {
	default =nil,
  ["Gregarious Grell"] = { "promises to do your bidding.", 
    },  
  ["Lil' K.T."] = {  "will not hear your pleads.",},
},
POINT = {
	default = nil,
  ooze = {  "leans its upper half towards you to point back.", },

},
POKE = {
	default = {
		"looks at you. Yes?",
	},
	cat = {
		"looks at you. Meow?",
	},
	snake = {
		"looks at you. hiss?",
	},
	bird = {  "flies away startled.",},
	evil = {  "looks at you with irritation. What?",},
	["flying insect"] = {  "searches your finger for food.", },
	humanoid = {  "looks at you and says, \"Hey, not so hard. That hurt.\"", },
	ooze = {  "has an indentation where you poked it, and then suddenly springs back into normal shape.", },
},
PONDER = {
	default = nil,
},
POUNCE = {
	default = nil,
	beast = {  "is pounced and rolls over with you.", },
	bird = { "squawks and flaps its wings trying to free itself.", },
	humanoid = { "is pounced and wants you to remove yourself off.", },
    ["Gregarious Grell"] = { "screams, \"Not me! I have children!\"", 
    },
	["Lil' K.T."] = { "freezes you with a Frost Blast before you reach him.",},
    ["Lil' Ragnaros"] = {   "sends you flying with a Lava Wave."},
},
POUT = {
	default =nil,
  ["Gregarious Grell"] = { "comforts you.", 
    },  
  ["Lil' K.T."] = {  "has no time for babies and shoos you away.",},
  ["Lil' Ragnaros"] = {   "understands insects are weak."},
},
PRAISE = {
	default =nil,
  ["Gregarious Grell"] = { "is happy to be praised.", 
    },  
  ["Lil' K.T."] = {  "grins, absorbing your praise into his ego.",},
  ["Lil' Ragnaros"] = {   "cackles."},
},
PRAY = {
	default =nil,
    ["Gregarious Grell"] = { "tries to make out your gesture.", 
    },
	["Lil' K.T."] = {  "suggests you join the Cult of the Damned for better results.",},
    ["Lil' Ragnaros"] = {   "commends your worship."},
},
PROUD = {
	default = nil,
	beast = {  "holds head high proudly.", },			
},
PULSE = {
	default = nil,
},
PUNCH = {
	default =nil,
	["flying insect"] = {  "easily evades the attack and flies about you.", },
  ["Gregarious Grell"] = { "is hit for 5 Physical.", 
    },  
  ["Lil' K.T."] = {  "is already tapped by another player.",},
  ["Lil' Ragnaros"] = {   "blocks your punch with Sulfuras."},
},
PURR = {
	default = {
		"coos.",
	},
	snake = {
		"hisses.",
	},
	cat = {  "purrs back at you.", },
	evil = {  "looks at you strangely.",},
	humanoid = {  "wants to know if you're being flirty.", },
	mech = {  "beeps back at you with a series of light notes.", },
},
PUZZLE = {
	default =nil,
	humanoid = { response = "is a puzzle like in Zelda!", },
	mech = {  "attempts to recalibrate its interaction subroutines.", },
	["Lil' K.T."] = {  "didn't expect you to comprehend his greatness.",},
    ["Lil' Ragnaros"] = {   "didn't expect you to comprehend his evil scheme."},
},
RAISE = {
	default =nil,
  ["Gregarious Grell"] = { "tells you that command doesn't work in %t.", 
    },  
  ["Lil' K.T."] = {  "smiles. \"Ah, volunteers. Most excellent.\"",},
},
RASP = {
	default =nil,
  ["Gregarious Grell"] = { "asks, \"Why can't we just get along?\"", 
    },  
  ["Lil' K.T."] = {  "yells, \"Burn!\"",},
},
READY = {
	default = nil,
},
REGRET = {
	default = nil,
    ["Gregarious Grell"] = { "regrets signing over %t's services.\"", 
    },
	["Lil' K.T."] = {  "highly doubts he will.",},

},
REVENGE = {
	default = nil,
  ["Gregarious Grell"] = { "says, \"There are bigger minions more suited for this job.\"", 
    },  
  ["Lil' K.T."] = {  "thinks your vows are lovely and has yet to work on his.",},
  ["Lil' Ragnaros"] = {   "proposes a pact to set fire to the world."},
},
ROAR = {
	default =nil,
	cat = {  "flees.", },
	dino = {  "roars back ferociously.", },
	["Lil' K.T."] = {  "asks if you are done making a ruckus",},
    ["Lil' Ragnaros"] = {   "has seen bigger dogs in The Firelands."},
},
ROFL = {
	default =nil,
	ooze = {  "shakes as if it were laughing heartily.", },
    ["Gregarious Grell"] = { "screams, \"HELP! Master is down!\"", 
    },
	["Lil' K.T."] = {  "kicks you while you're down.",},
    ["Lil' Ragnaros"] = {   "yells, \Victory is mine!\ "},
},
ROLLEYES = {
	default = nil,
  evil = {  "glowers at you.", },
},
RUDE = {
	default = nil,
  ["Gregarious Grell"] = { "asks, \"Why can't we just get along?\"", 
    },  
  ["Lil' K.T."] = {  "threatens to freeze the blood in your veins.",},
  ["Lil' Ragnaros"] = {   "smacks Sulfuras against your knee."},
},
RUFFLE = {
	default = nil,
  ["Gregarious Grell"] = { "screams, \"NOT THE EARRINGS!\"", 
    },  
  ["Lil' K.T."] = {  "says, \"No, not the hat! Takes ages to straighten.\"",},
  ["Lil' Ragnaros"] = {   "says, \You will burn your fingers insect!"},
},
Random = {
	default = {
		"does a little dance.","does a little dance.",
		"is excited to see new places.",
		"looks around at all the people.",
		"sits on the floor.",
		"reads a very good book.",
		"takes some pictures.",
		"wants to know when its dinner time.",
		"thinks you have very nice hair.",
		"charges into battle.",
		"looks cute.","looks cute.","looks cute.",
		"takes a long drink.",
		"has a cup of tea.","has a cup of tea.",
		"plants a garden.",
		"does a jig.",
		"goes off the deep end.",
		"sings.","sings.","sings.","sings.","sings.","sings.","sings.",
		"thinks all you need is love.",
		"blinks.","blinks.","blinks.","blinks.",
		"will tag along with you.",
		"loves you.","loves you.","loves you.",
		"adores you.","adores you.",
		"admires you.","admires you.",
		"winks.","winks.","winks.",
		"hides their loot.",
		"thinks the Lich King is scary.",
		"wants to go on an adventure.",
		"coos.",
		"giggles.",
		"wants to go adventuring.",
		"is tired.",
		"needs a nap.",
		"would like to take a break.",
		"wants to go mining.",
		"would like to try out skinning.",
		"wants to learn about troll history.",
		"loves archeology.",
		"loves the Feast of Winter Veil.",
		"loves Brewfest.",
		"wants a drink.",
		"waves at everybody.",
		"puzzles over your outfit.",
		"plays with a small ball.",
		"thinks about the meaning of life.",
		"is intrested by the number 23.",
		"squeaks.",
		"daydreams.",
		"would like to be fed.",
		"dreams about being an adventurer.",
		"dreams about fighting the Lich King.",
		"dreams about being a fashion model.",
		"dreams about being a fire fighter.",
		"dreams about being a rock star.",
		"dreams about little pink fluffy clouds.",
        "dreams about ruling Azeroth.",
		"loves the color green.",
		"loves the color purple.",
		"stands up and waves.",
		"wants a glass of water.",
		"sits down comfortably.",
		"spits on the ground.",
		"curls up with a good book.",
		"needs a good therapist after the last adventure.",
		"looks around in awe.",
		"looks around scared.",
		"looks around.",
		"looks around in confusion.",
		"is confused at the current situation.",
		"would like a cookie.",
		"would like some cake.",
		"would like some milk.",
		"understands that there is no spoon.",
		"wants to go play the auction house.",
		"can't stand waiting around.",
		"loves pumpkin pie.",
		"can't wait for the next fishing tournament.",
		"would love to go fishing.",
		"would love to do some cooking.",
		"dreams of far away lands.",
		"wants to fly a kite.",
		"eats some food.",
		"prepares a Savage Feast, for 1.",
		"wonders why we are here.",
		"crys.",
		"loves you!",
		"loves everybody!",
		"hates this place.",
		"loves this place.",
		"wants to bask in the glory of Onyxia.",
		"wants a pet biscuit.",
		"loves Chinchillas!",
		"climb's on your shoulders.",
		"chases a bug.",
		"paints.",
		"wonders why Gronn was demoted to captain hook from Dragonslayer.",
		"wants to grow up to be a dragon.",
		"thinks therefore is.",
		"ama il formaggio.",
		"wants to find true love.",
	},
  default_Locations = {
		"would like to visit the Eastern Kingdoms.",
		"would like to go see the Dwarves at Dun Morogh.",
		"would like to visit Elwynn Forest.",
		"would like to visit Eversong Woods.",
		"would like to visit Gilneas.",
		"would like to visit Tirisfal Glades.",
		"would like to visit Ghostlands",
		"would like to visit Loch Modan",
		"would like to frolic in Silverpine Forest.",
		"would like to visit Westfall.",
		"would like to run along the shore in Redridge Mountains.",
		"would like to visit Duskwood.",
		"would like to visit Hillsbrad Foothills.",
		"would like to take a mudbath in the Wetlands.",
		"would like to visit Alterac Mountains.",
		"would like to visit Arathi Highlands.",
		"would like to visit The Hinterlands.",
		"would like to visit Stranglethorn.",
		"would like to become a zombie in Western Plaguelands.",
		"would like to bring the light to the Eastern Plaguelands.",
		"would like to visit Badlands.",
		"would like to visit Searing Gorge.",
		"would like to visit Burning Steppes.",
		"would like to swim along the shore in the Swamp of Sorrows.",
		"would like to visit The Blasted Lands.",
		"would like to visit Blackrock Mountain.",
		"would like to visit Karazan.",
		"would like to visit Isle of Quel'Danas",
		"would like to visit Twilight Highlands.",
		"would like to visit Tol Barad.",
		"would like to explore Azuremyst Isle.",
		"would like to explore Durotar.",
		"would like to explore Mulgore.",
		"would like to explore Teldrassil.",
		"would like to explore Bloodmyst Isle.",
		"would like to frolic in Darkshore.",
		"would like to explore Azshara.",
		"would like to explore Northern Barrens.",
		"would like to explore Ashenvale.",
		"would like to explore Stonetalon Mountains.",
		"would like to explore Desolace.",
		"would like to explore Southern Barrens.",
		"would like to explore Dustwallow Marsh.",
		"would like to explore Feralas.",
		"would like to explore Thousand Needles.",
		"would like to explore Tanaris.",
		"would like to explore Felwood.",
		"would like to see a dino in Un'goro Crater.",
		"would like to explore Winterspring.",
		"would like to explore Silithus.",
		"would like to explore Moonglade.",
		"would like to burn Mount Hyjal.",
		"would like to see Uldum.",
		"would like to explore Ahn'Qiraj.",
        "would like to never Ever EVER see Pandaria.",
		"is interested in seeing Outland.",
		"dreams about seeing the Dark Portal.",
		"wants to avoid Hellfire Peninsula.",
		"wants to avoid Zangarmarsh.",
		"loves Terokkar Forest.",
		"sings about Nagrand.",
		"thinks Blade's Edge Mountains is the coolest.",
		"would like to see if the story's about Netherstorm are true.",
		"asks if it really is always dark in Shadowmoon Valley.",
		"needs a coat to visit Borean Tundra.",
		"would like to see the Howling Fjord.",
		"wonders what Dragonblight is like.",
		"wonders what Grizzly Hills is like.",
		"would like to see Zul'Drak.",
		"would like to see Sholazar Basin.",
		"would like to see Storm Peaks.",
		"would like to see Crystalsong Forest.",
		"would like to see Hrothgar's Landing.",
		"thinks Icecrown is a scary place.",
		"needs a coat to visit Wintergrasp.",
		"thinks Karazhan is a long way aways.",
		"wonders if they ever found the Lost Isles.",
		"would like to see Vashj'ir .",
        "would like to raid Icecrown Citadel.",
        "would like to raid The Firelands.",
        "would like to raid Dragon Soul.",
        "would like to visit the Magical Menagerie.",
        "thinks the vale of Eternal Blossoms is neat.",
        "never wants to visit the Kun-Lai Summit.",
        "likes Townlong Steepes.",
        "wonders how the Wandering Isle wanders?",
        "would like to frolic in the Jade Forest.",
        "would like to frolic in the Krasarang Wilds.",
        "would like to burn the Dread Wastes to the ground.",
        "would like to dance in the thunder on the Isle of the Thunder King.",
        "would like to bask in the glory of the Isle of Giants.",
        "wants to live forever on the Timeless Isle.",
        "wants to sore with the wind in the Valley of the Four Winds.",
        "would like to explore the Veiled Stair",
        "would like to see the world from the top of the Veiled Stair",
  },
  default_Silly = {

		"wonders how the postal system works.",
		"thinks you should send your friends some mail.",
		"looks at all the lonely people.",
		"reads a comic.",
		"wonders what the secret sauce is made from.",
		"is concerned about the political state of affairs.",
		"plays catch.",
		"plays cards.",
		"plays backgammon.",
		"plays poker.",
		"plays jump rope.",
		"plays with a hula-hoop.",
		"plays 20 questions.",
		"plays air guitar.", "plays air guitar.",
		"rocks out.",
		"gets down.",
		"party's!",
		"dreams of being a pirate.",
		"is a ninja.",
        "wonders what Mr.Bigglesworth is doing right now.",
		"waves their hands in the air like they just don't care.",
		"wants their noms.",
		"thinks that the nightelf mohawk is the coolest.",
		"pretends to be a rocketship.  VROOOMMM",
		"thinks the Iron Horde are a bunch of silly billys.",
		"eats some hay, even though hay is for horses.",
		"picks a peck of pickled peppers",
		"twerks.",
		"shakes it like they just don't care.",
		"doesn't believe in ROUS.",  
		"says \"Say 'ello to my little friend!\"",
		"says \"You idiots! These are not them! You've captured their stunt doubles!\"",
		"says \"Gentlemen, you can't fight in here! This is the War Room.\"",
		"says \"No, now go away, or I shall taunt you a second time.\"",
		"says \"It's where I keep all my things. Get a lot of compliments on this. Plus, it's not a man-purse. It's called a satchel. Indiana Jones wears one.\"",
		"says \"Are you crying? There's no crying! There's no crying in the World of Warcraft!\"",
		"says \"Yeah, well. The Dude abides.\"",
		"says \"You brought the Pomeranian bowling?\"",
		"says \"I'll be back!\"",
		"says \"Keep it secret!  Keep it Safe!\"",
		"quotes \"Death need not concern us because when we exist death does not, and when death exists we do not.\"",
		"quotes \"Man is the measure of all things.\"",
		"quotes \"A categorical imperative would be one which represented an action as objectively necessary in itself, without reference to any other purpose.\"",
		"quotes \"Man is born free and is everywhere in chains.\"",
		"quotes \"The unexamined life is not worth living.\"",
		"quotes \"I think therefore I am.\"",
		"quotes \"Entities should not be multiplied unnecessarily.\"",
		"quotes \"Do unto others as you would have them do unto you.\"",
		"quotes \"All you need is love, love. Love is all you need.\"",
		"quotes \"We don't go do stupid things when somebody yells, 'For the Horde'.\"",
		"quotes \"Noble countrymen, evil is upon us. Darkness has befallen our shores. Rise and slay thy enemies… strike, strike so others shall live. The meek shall not fade into the night… live my brethren, live.\"",
		"says \"It's been a hard day's night.\"",
		"plays Hearthstone.",
		"wants to join the brawlers guild.",
		"thinks Blingtron is overcompensating.",
		"has a crush on Jaina Proudmoore.",
		"wants to be just like Thrall!",
		"can take Garrosh Hellscream in a fight.",
		"wonders what Valeera Sanguinar is doing now.",
		"thinks Pandas are silly and inapropriate.",
		"wants to harness time travel to re-write history as well!",
		"casts Armageddon",
		"laughs evilly while rubbing hands together.",
		"is the best pet ever!",
		"informs everybody that yellow5 is poison!",
		"wants to make sure you vaccinated!",
		"says \"You want the truth!  You can't handle the truth!\"",
		"says \"Wants to boldly go where no pet has gone before!\"",
		"says \"ceci n'est une pipe\"",
		"says \"In bocca al lupo!\"",
		"says \"YOLO\"",
		"dreams of being a little pony.",
		"get's drunk.",
		"prepares a roast chicken.",
		"bag is bigger on the inside!",
		"says \"is that a blue box?\"",
		"thinks it's all about that base.",
		"poops.",
		"busts a move!",
		"grows a little garden",
		"says \"NI!\n",
		"thinks sometimes a cigar is just a cigar.",
		"says \"go Red Sox!\"",
		"quotes \"Oh, that this too, too sullied flesh would melt\"",
		"quotes \"To be, or not to be, that is the question— Whether 'tis Nobler in the mind to suffer\"",
		"quotes \"All the world’s a stage, And all the men and women merely players\"",
		"quotes \"Once more unto the breach, dear friends, once more\"",
		"wonders why he wore the red shirt today.",
		"thinks I'm a battle pet not a doctor!",
		"wants to protect the garrison.",
		 "thinks how many more of these Abrogator stones do we need?",
		 "thinks Arch Mage Khadgar should do his own dirty work.",
		 "wants to join the burning legion",
		 "yells \"For the Alliance\"",
		 "yells \"For the Horde\"",
		 "wants to go fight in the Highmaul arena.",
		 "loves Deathwing.",
		 "wants to tank.",
		 "thinks podlings are mean.",
		 "justifies existence by deeps score.",
		 "takes a deep breath!",
		 "says \"Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn.\"",
		 "whispers \"They are coming for you...\"",
		 "whispers \"Kill them all... before they kill you...\"",
		 "whispers \"Trust is your weakness...\"",
		 "whispers \"Hope is an illusion...\"",
		 "whispers \"All that you know will fade...\"",
		 "whispers \"You are a pawn of forces unseen...\"",
		 "knows Yogg-Saron will destroy the world.",
		 "whispers \"You will betray your friends.\"",
		 "digs C'Thun's eye.",
		 "sees all!",
		 "rides a pale horse.",
		 "throws a dance party!",
  },
  default_Songs={
		"sings, \"I like tuna, I like chicken, I like liver, meow meow meow meow, meow meow meow meow.\"",
		"sings, \"It\'s not that easy being green, having to spend each day the color of the leaves, when I think it could be nicer being red, or yellow, or gold or something.\"",
		"sings, \"It\'s the hard-knock life for us! It\'s the hard-knock life for us! \'Steada treated, we get tricked! \'Steada kisses, we get kicked! It\'s the hard-knock life!\"",
		"sings with a computer voice, \"When I look out there, it makes me glad I\'m not you. I\'ve got experiments to run. There is research to be done on the people who are still alive. And believe me I am still alive.\"",
		"sings, \"Sunny day sweepin the clouds away, on my way to where the air is sweeet, can to tell me how to get, how to get to Sesame Street.\"",
		"sings, \"Do-do-do-do-do Dora! Do-do-do-do-do Dora! Dora Dora Dora the explorer! Boots, the super cool explora, Dora.\"",
		"sings, \"I\'ve got a lovely bunch of coconuts. There they are standing in a row. Big ones, small ones, some as big as your head!\"",
		"sings, \"Jingle bell, jingle bell, jingle bell rock.  Jingle bells swing and jingle bells ring, snowing and blowing up bushels of fun, now the jingle hop has begun.\"",
		"sings, \"Imagine all the people living life in peace. You may say I\'m a dreamer but I\'m not the only one. I hope someday you\'ll join us and the world will be as one.\"",
		"sings, \"Cause I\'m the Boogie Man and if you aren\'t shakin\' then there\'s something very wrong. Cause this may be the last time now that you hear the boogie song. Oooh.\"",
		"sings, \"Get up, get on up, stay on the scene, like a sex machine.\"",
		"sings, \"I wanna be yours pretty baby, yours and yours alone. I\'m here to tell ya honey that I\'m bad to the bone. Bad to the bone. B-b-b-bad.\"",
		"sings, \"You just call on me brother when you need a hand. We all need somebody to lean on. I just might have a problem that you\'ll understand. We all need somebody to lean on.\"",
		"sings, \"Doo doo doo doo doo doo I\'m singing in the rain. Just singing in the rain. What a glorious feeling, I\'m happy again.\"",
		"sings, \"War, huh, yeah! What is it good for! Absolutely nothing! Say it again, you all.\"",
		"sings, \"Don\'t you want somebody to love. Don\'t you need somebody to love. Wouldn\'t you love somebody to love. You better find somebody to love, love, love.\"",
		"sings, \"But oh it\'s too hot, too hot lady. I gotta run for shelter, I gotta run for shade. It\'s too hot, too hot lady. Gotta cool this anger. What a mess we made.\"",
		"sings, \"But nothing ever happens and I wonder, I wonder how, I wonder why, yesterday you told me about the blue, blue sky and all that I can see is just another lemon tree.\"",
		"sings, \"Oohh ooo. Oohh ooo. What would Christmas be like without you here, singing at the bottom of the mistletoe waiting for you to come home.\"",
		"sings, \"Little darling, its been a long cold lonely winter,Little darling, it feels like years since its been here, Here comes the sun, here comes the sun,and I say its all right.\"",
		"sings, \" I want your loving, And I want your revenge, You and me could write a bad romance.\"",
		"sings, \"Take on me, take me on, I'll be gone, In a day or two.\"",
		"sings, \"99 dreams I have had, In every one a red balloon, Its all over and I'm standin' pretty, In this dust that was a city.\"",
		"sings, \"I like big butts and I can not lie, you other brothers can't denie, that when a girl walks in with an itty bitty waist and a round thing in your face, you get sprung!\"",
		"sings, \"I like'em round and big,And when I'm throwin' a gig,I just can't help myself,I'm actin like an animal.\"",
		"sings, \"I'm a barbie girl, in a barbie world. Life in plastic, its fantastic!\"",
		"sings, \"Because the night belongs to lovers. Because the night belongs to lust. Because the night belongs to lovers. Because the night belongs to us.\"",
		"sings, \"How can we dance when our earth is turning, How do we sleep while our beds are burning.\"",
		"sings, \"Do you think you're better off alone? Talk to me...Ohhh, talk to me.\"",
		"sings, \"'Cause its a bittersweet symphony, this life. Trying to make ends meet.\"",
		"sings, \"I'm blue dabba dee-a dabba da da ba dee dabba da.\"",
		"sings, \"And I said what about \"Breakfast at Tiffany's?\"\"",
		"sings, \"If you want it baby you've got it. Just bust a move!\"",
		"sings, \"Come my lady. Come come my lady. you're my butterfly.\"",
		"sings, \"Butterfly kisses after bedtime prayer, Stickin little white flowers all up in her hair.\"",
		"sings, \"Here in my car, I feel safest of all, I can lock all my doors ,Its the only way to live ,In cars \"",
        "sings, \"Never gonna give you up, never gonna let you down, never gonna run around and desert you, never gonna make you cry, never gonna say goodbye, never gonna tell a lie and hurt you.\"",
        "sings, \"what is love, baby don't hurt me, don't hurt me, no moooore.\"",
        "sings, \"Love bug, best kind of bug around (it’s a love bug, it’s a love bug), Love bug, best kind of bug—where the hugs come from.\"",
		"sings, \"Let it go, let it go! Turn away and slam the door. I don't care what they're going to say. Let the storm rage on. The cold never bothered me anyway.\"",
		"sings, \"Let me tell you how it will be, there's one for you and nineteen for me, cause I'm the Taxman. \"",
		"sings, \"And in the end, the love you take is equal to the love you make.\"",
		"sings, \"Ob-la-di, Ob-la-da, life goes on.\"",
		"sings, \"Let it be, let it be. There will come an answer, let it be.\"",
		"sings, \"Life is very short and there's no time for fussing and fighting my friend. \"",
		"sings, \"Black, white, green, red, can I take my friend to bed? \"",
		"sings, \"I get by with a little help from my friends.\"",
		"sings, \"In my hour of darkness, she is standing right in front of me, speaking words of wisdom, let it be.\"",
		"sings, \"Blackbird singing in the dead of night, take these broken wings and learn to fly. All your life, you were only waiting for this moment to arrive, you were only waiting for this moment to be free.\"",
		"sings, \"I am the walrus, googoog'joob, googoog'joob.\"",
				"sings, \"I'd like to be under the sea in an Octopus's garden in the shade.\"",
				"sings, \"Yesterday all my troubles seemed so far away. Now it looks as though they're here to stay. Oh, I believe in yesterday.\"",
				"sings, \"Honey pie, you are making me crazy. I'm in love, but I'm lazy. \"",
				"sings, \"Ah, look at all the lonely people.\"",
				"sings, \"Please, please me, oh yeah, like I please you.\"",
				"sings, \"I get high with a little help from my friends.\"",
				"sings, \"It's getting better all the time, can't get no worse. \"",
				"sings, \"Here comes the sun, it's alright.\"",
				"sings, \"The sun is up, the sky is blue, it's beautiful, and so are you.\"",
				"sings, \"He's a real no where man, sitting in his no where land, making all his no where plans for nobody.\"",
				"sings, \"I buried Paul.\"",
				"sings, \"I'd love to turn you on.\"",
		"sings, \"We could have had it all, (You're gonna wish you never had met me). Rolling in the deep\"",
		"sings, \"And we'll never be royals.  It don't run in our blood, That kind of luxe just ain't for us.\"",
		"sings, \"We didn't start the fire. It was always burning. Since the world's been turning\"",
		"sings, \"Sweet dreams are made of this. Who am I to disagree? I travel the world. And the seven seas, Everybody's looking for something.\"",
		"sings, \"I just wanna use your love tonight. I don't wanna lose your love tonight\"",
		"sings, \"Turn around bright eyes, Every now and then I fall apart\"",
		"sings, \"It's the eye of the tiger, It's the thrill of the fight, Risin' up to the challenge",
		"sings, \"Every breath you take. Every move you make. Every bond you break. Every step you take. I'll be watching you.\"",
		"sings, \"Do you come from a land down under? Where women glow and men plunder? Can't you hear, can't you hear the thunder? You better run, you better take cover\"",
		"sings, \"It's gonna take a lot to drag me away from you. There's nothing that a hundred men or more could ever do. I bless the rains down in Africa. Gonna take some time to do the things we never had\"",
		"sings, \"Ah, push it - push it good. Ah, push it - push it real good. Ah, push it - push it good. Ah, push it - p-push it real good\"",
		"sings, \"Woah, we're half way there. Woah, livin' on a prayer. Take my hand, we'll make it I swear. Woah, livin' on a prayer\"",
		"sings, \"When you call my name it's like a little prayer. I'm down on my knees, I wanna take you there\"",
		"sings, \"Oh, I wanna dance with somebody. I wanna feel the heat with somebody. Yeah, I wanna dance with somebody. With somebody who loves me\"",
		"sings, \"What rymes with hug me?\"",
		"sings, \"Take me on (take on me). I'll be gone. In a day or two\"",
		"sings, \"Puff the Magic Dragon Live's by the Sea.\"",

		
  },
	cat = {
		"purrs.",
		"plays with a ball.",
		"rubs against your leg.",
		"decides this is a good place to sleep.",
		"naps.",
		"purrs.",
		"paws at your pant leg.",
	},
	snake = {
		"hisses.",
		"slides around the floor.",
		"looks around for a mouse to eat.",
		"decides this is a good place to sleep.",
		"naps.",
		"hisses.",
		"slides around your pant leg.",
	},
},
SAD = {
	default = nil,
	ooze = {  "melts into a depressing looking puddle.", },
    ["Gregarious Grell"] = { "comforts the master.", 
    },
},
SALUTE = {
	default =nil,
	beast = {  "salutes back with attentiveness.", },
	bird = {  "raises one wing as a salute.", },
	mech = {  "salutes and is awaiting orders.", },
    ["Gregarious Grell"] = { "informs you %t is ready for action.", 
    },
	["Lil' K.T."] = {  "recognizes you as a member of his fan club.",},
    ["Lil' Ragnaros"] = {   "promotes you to lieutenant of the flame."},
},
SCARED = {
	default = nil,
  ["Gregarious Grell"] = { "shouts, \"Let's get out of here! FAST!\"", 
    },  
  ["Lil' K.T."] = {  "wiggles his fingers and taunts you with ghost noises.",},
  ["Lil' Ragnaros"] = {   "flexes his mucles before you."},
},
SCOFF = {
	default = {
		"jeers right back at you.",
	},
},
SCOLD = {
	default = {
		"hangs head dejectedly.",
	},
  ["Lil' K.T."] = {  "mocks your scolding.",},
  ["Lil' Ragnaros"] = {   "asks you if you din'd wipe enough in The Firelands."},
},
SCOWL = {
	default =nil,
["Lil' K.T."] = {  "tries to irk you on.",},
["Lil' Ragnaros"] = {   "prepares Sulfuras for an attack."},
},
SCRATCH = {
	default = {
		"says \"Ow!\"",
	},
	cat = {
		"says \"meow?!\"",
	},
	snake = {
		"says \"hiss?!\"",
	},
	cat = {  "scratch back. Mrreoowww.", },
    ["Gregarious Grell"] = { "screams, \"THIS WAS NOT IN MY CONTRACT!\"", 
    },
	["Lil' K.T."] = {  "glances him for 1 Physical.",},
    ["Lil' Ragnaros"] = {   "glances him for 1 Physical."},
},
SEARCH = {
	default = nil,
	beast = {  "might have picked up fleas again.", },
	ooze = {  "may have eaten your keys.", },
    ["Gregarious Grell"] = { "shouts, \"No master! %t is ticklish!\"", 
    },
	["Lil' K.T."] = {  "hides his loot table. NO! Not going to happen.",},
    ["Lil' Ragnaros"] = {   "hides his loot table. NO! Not going to happen."},
},
SEXY = {
	default = nil,
["Gregarious Grell"] = { "looks rather hot with earrings.", 
    },    
["Lil' K.T."] = {  "is rather devilish isn't he. So evil, its sexy!",},
["Lil' Ragnaros"] = {   "is so hot, not even lava compares."},

},
SHAKE = {
	default = nil,
  ["Lil' K.T."] = {  "fires a Frostbolt at that huge target.",},
  ["Lil' Ragnaros"] = {   "sends out a Sulfuras Smash."},
},
SHAKEFIST = {
	default = {
		"is ready! Bring it!",
	},
	cat = {
		"stands on its hind legs and roars!",
	},
},
SHIFTY = {
	default = {
		"wants to know what's going down.",
	},
  ooze = {  "darts from side to side.", },
},
SHIMMY = {
	default =nil,
  ["Lil' K.T."] = {  "doesn't think you're very good at dancing.",},
  ["Lil' Ragnaros"] = {   "is clearly not impressed."},
},
SHIVER = {
	default =nil,
	beast = {  "cuddles close to warm you.", },
	cat = {  "brushes against your leg.", },
	ooze = {  "shivers next to you.", },
    ["Gregarious Grell"] = { "asks, \"Would you like me to blast you with a Firebolt, master?\"", 
    },
	["Lil' K.T."] = {  "checks to see if he is on AC mode.",},
},
SHOO = {
	default = {
		"is shooed away.",
	},
	cat = {  "brushes against your leg and purrs.",},
    ["Gregarious Grell"] = { "says, \"Argh! I feel so used!\"", 
    },
	["Lil' K.T."] = {  "will not be shooed away by a mere mortal!",},
    ["Lil' Ragnaros"] = {   "the realm of fire will consume you!"},
},
SHRUG = {
	default = nil,
},
SHUDDER = {
	default = nil,
},
SHY = {
	default = nil,
},
SIGH = {
	default = {
		"wants to know what's wrong.",
	},
	cat = {
		"says \"meow?\".",
	},
	snake = {
		"says \"hiss?\".",
	},
  humanoid = {  "wants to know what's wrong.", },
},
SIGNAL = {
	default = nil,
},
SILENCE = {
	default = {
		"tries to keep it down.",
	},
	cat = {
		"says \"meow?\".",
	},
	snake = {
		"says \"hiss?\".",
	},
	["flying insect"] = {  "flies around your ear. Buzz buzz.", },
	inanimate = {  "is unaffected.", },		
	mech = {  "goes into standby mode.", },
    ["Gregarious Grell"] = { "Has a Firebolt interrupted.", 
    },
	["Lil' K.T."] = {  "has a Frostbolt interrupted.",},
    ["Lil' Ragnaros"] = {   "is immune to interrupts."},
},
SING = {
	default = {
		"sings with you.",
	},
	cat = {
		"sings, \"I like tuna, I like chicken, I like liver, meow meow meow meow, meow meow meow meow.\"",
	},
	snake = {
		"sings, \"I want you to see your body move like a snake, yeah.\"",
    "raises its head and sways side to side to the rhythm.",
	},
	inanimate = {  "is unaffected.", },							
	ooze = {  "responds positively, bouncing up and down to the rhythm.", },			
	["Argent Gruntling"] = {  "sings, \"It\'s not that easy being green, having to spend each day the color of the leaves, when I think it could be nicer being red, or yellow, or gold or something.\"",},
	["Argent Squire"] = {  "sings, \"It\'s the hard-knock life for us! It\'s the hard-knock life for us! \'Steada treated, we get tricked! \'Steada kisses, we get kicked! It\'s the hard-knock life!\"",},
    ["Bananas"] = {  "sings, Yes, I have no bananas, I have no bananas today. Doo doo doo doooo\"",},
    ["Blue Clockwork Rocket Bot"] = {  "sings with a computer voice, \"When I look out there, it makes me glad I\'m not you. I\'ve got experiments to run. There is research to be done on the people who are still alive. And believe me I am still alive.\"",},
	["Clockwork Rocket Bot"] = {  "sings with a computer voice, \"We are human, MmmaMmmaMmMMMHHhh, after all, MmmaMmaMMmmMMMHHH, flesh encumbered,  MmmaMmmaMmMMMHHhh, after all.\"",
	 },		
	["Curious Oracle Hatchling"] = {  "sings, \"Sunny day sweepin the clouds away, on my way to where the air is sweeet, can to tell me how to get, how to get to Seasame Street.\"",
			 },
	["Curious Wolvar Pup"] = {  "sings, \"Do-do-do-do-do Dora! Do-do-do-do-do Dora! Dora Dora Dora the explorer! Boots, the super cool explora, Dora.\"",
		 },
    ["Deathy"] = {  "sings, \"Stacy\'s mom has got it goin' on, she's all I want and I\'ve waited for so looong.\"",
		 },
	["Ethereal Soul-Trader"] = {  "sings, \"I\'ve got a lovely bunch of coconuts. There they are standing in a row. Big ones, small ones, some as big as your head!\"",
	},
	["Father Winter\'s Helper"] = {  "sings, \"Jingle bell, jingle bell, jingle bell rock.  Jingle bells swing and jingle bells ring, snowing and blowing up bushels of fun, now the jingle hop has begun.\"",
	},
    ["Gregarious Grell"] = { "sings, \"snroh htiw dog a ,sevooh htiw dog a, snroh htiw dog a ,sevooh htiw dog A.\"", 
    },
	["Grunty"] = {  "sings, \"I am more than a fish. I am more than a man. Death will rise from the tide. I am murloc! Ahhwrlrwlrwlrwlrwl.\"",
	 },
	["Kirin Tor Familiar"] = {  "sings, \"Imagine all the people living life in peace. You may say I\'m a dreamer but I\'m not the only one. I hope someday you\'ll join us and the world will be as one.\"",
	},
	["Lil' K.T."] = {  "sings, \"Cause I\'m the Boogie Man and if you aren\'t shakin\' then there\'s something very wrong. Cause this may be the last time now that you hear the boogie song. Oooh.\"", },
	["Lil' Ragnaros"] = {   "sings, \"we din\'d start the fire, it was always burning, since the world's been turning.\"", },
    ["Lil' Smoky"] = {  "sings, \"I\'m a sex machine ready to reload like an atom bomb about to oh oh oh oh explode! I'm burning through the sky, yeah! 200 degrees, that\'s why they call me Mr. Fahrenheit.\"",},
	["Mini Diablo"] = {  "sings, \"I wanna be yours pretty baby, yours and yours alone. I\'m here to tell ya honey that I\'m bad to the bone. Bad to the bone. B-b-b-bad.\"",
	 },
	["Mini Tyrael"] = {  "sings, \"You just call on me brother when you need a hand. We all need somebody to lean on. I just might have a problem that you\'ll understand. We all need somebody to lean on.\"",},
	["Murky"] = {  "sings in murloc, \"Doo dloo doo doo doo doo I\'m singing in the rain. Just singing in the rain. What a glorious feeling, I\'m happy again.\"",},
	["Pandaren Monk"] = {  "sings, \"War, huh, yeah! What is it good for! Absolutely nothing! Say it again, you all.\"",},
	["Peddlefeet"] = {  "sings, \"Don\'t you want somebody to love. Don\'t you need somebody to love. Wouldn\'t you love somebody to love. You better find somebody to love, love, love.\"",
	},
				["Scorchling"] = {  "sings, \"But oh it\'s too hot, too hot lady. I gotta run for shelter, I gotta run for shade. It\'s too hot, too hot lady. Gotta cool this anger. What a mess we made.\"",},
				["Teldrassil Sproutling"] = {  "sings, \"But nothing ever happens and I wonder, I wonder how, I wonder why, yesterday you told me about the blue, blue sky and all that I can see is just another lemon tree.\"",},
				["Winter's Little Helper"] = {  "sings, \"Oohh ooo. Oohh ooo. What would Christmas be like without you here, singing at the bottom of the mistletoe waiting for you to come home.\"",
	},
	dragon = {
		"sings, \"Puff the magic dragon Live's by the Sea.\"",
	},

},
SIT = {
	default = {
		"sits down.",
	},
	cat = {
		"sits on %t's lap.",
	},
},
SLAP = {
	default = {
		"says \"Ow!\"",
	},
	cat = {
		"cringes.",
	},
	snake = {
		"cringes.",
	},
    
	["flying insect"] = {  "is swatted down. Mayday! Mayday!.", },
    ["Gregarious Grell"] = { "is hit for 3 Physical.", },
	["Lil' K.T."] = {  "parries your attack.",},
    ["Lil' Ragnaros"] = {   "laughs while you burn your hand."},
},
SLEEP = {
	default = nil,
	ooze = {  "takes the shape of a mini Night Elf female with two green glowsticks and goes off to a rave.", },
    ["Lil' Ragnaros"] = {   "puny insect! sleep is for the weak!"},
},
SMACK = {
	default = nil,
["Gregarious Grell"] = { "is hit for 4 Physical.", 
    },    
["Lil' K.T."] = {  "is hit for 2 Physical.",},
["Lil' Ragnaros"] = {   "dodges and strikes back with Sulfuras."},
},
SMILE = {
	default = {
		"smiles back.",
	},
  ["Lil' K.T."] = {  "smiles with a hint of evil and a pinch of diabolical",},
  ["Lil' Ragnaros"] = {   "does not know what this so called smile is."},
},
SMIRK = {
	default = nil,
},
SNAP = {
	default = nil,
},
SNARL = {
	default = nil,
  ["Lil' K.T."] = {  "is shaking in his chains. So scary. That was sarcasm.",},
},
SNEAK = {
	default = nil,
  ["Lil' K.T."] = {  "sees you in the corner of his eyes. You can't do that in combat.",},
},
SNEEZE = {
	default = nil,
  ["Gregarious Grell"] = { "asks, \"Is master coming down with a cold?\"", 
    },  
  ["Lil' K.T."] = {  "thinks you should see a doctor. Luckily, he has a PHD in Pwnology.",},
  ["Lil' Ragnaros"] = {   "yes, keep inhaling my sweet sulfur."},
},
SNICKER = {
	default = {
		"cries.",
	},
},
SNIFF = {
	default = nil,
},
SNORT = {
	default = nil,
},
SNUB = {
	default = nil,
  humanoid = {  "crosses arms and ignores you until you lose the attitude." },
  ["Lil' K.T."] = {  "cannot be snubbed by you. It\'s Lil\' K.T. that snubs you, sir!",},
},
SOOTHE = {
	default = nil,
},
SPIT = {
	default =nil,
	humanoid = {  "insults you and spits back.", },
	ooze = {  "combines the spit into its slimey form and looks pleased. Ew!",
	},
    ["Gregarious Grell"] = { "yells, \"THIS WAS NOT IN MY CONTRACT!\"", 
    },
	["Lil' K.T."] = {  "snaps off the spit that froze on contact and glares at you.",},
    ["Lil' Ragnaros"] = {   "fall to your knees, mortal! This ends now!"},
},
SQUEAL = {
	default =nil,
},
STARE = {
	default =nil,
	ooze = {  "has two floating copper coins stuck in it that seem to stare back at you.", },
    ["Gregarious Grell"] = { "fidgets nervously.", 
    },
	["Lil' K.T."] = {  "stares you down with a cold, soul-piercing gaze.",},
    ["Lil' Ragnaros"] = {   "your judgement has come!"},
},
STINK = {
	default = nil,
	ooze = {  "oozes with exotic odors.", },
    ["Gregarious Grell"] = { "smells like a dead rat.", 
    },
	["Lil' K.T."] = {  "asks if you know that he is dead. You know, don\'t you?",},
    ["Lil' Ragnaros"] = {   "vaporates the sweet smell of sulfur."},
},
SURPRISED = {
	default = {
		"is full of surprises.",
	},
},
SURRENDER = {
	default =nil,
    
["Gregarious Grell"] = { "screams, \"FINALLY! Now I am master!\"", 
    },    
["Lil' K.T."] = {  "tells you to swear your allegiance to him.",},
["Lil' Ragnaros"] = {   "this is my realm!"},
},
SUSPICIOUS = {
	default =nil,
  ["Gregarious Grell"] = { "swears he only follows masters orders.", 
    },  
  ["Lil' K.T."] = {  "tells you there's nothing suspicious about the Cult of the Damned. It's legit!",},
  ["Lil' Ragnaros"] = {   "assures you %t not planning another comeback... for now."},
},
SWEAT = {
	default = nil,
},
TALKEX = {
	default = {
		"listens intently",
	},
evil = {  "thinks you should zip your lip like a padlock. Blah blah blah.",},
},
TALKQ = {
	default = nil,
},
TAP = {
	default = nil,
  ["Lil' K.T."] = {  "is undead and can take all of eternity, mortal.",},
  ["Gregarious Grell"] = { "is running around in a circle.", 
    }
},
TAUNT = {
	default = {
		"cowers in fear.",
	},
["Gregarious Grell"] = { "asks, \"Why does master taunt %t?\"", 
    },    
["Lil' K.T."] = {  "is now taunt immune!",},
["Lil' Ragnaros"] = {   "your arrogance will be purged in living flame!"},
},
TEASE = {
	default = nil,
},
THANK = {
	default = {
		"nods.",
	},
  ["Gregarious Grell"] = { "says, \"I only obey contract.\"", 
    },  
  ["Lil' K.T."] = {  "tells you the credit goes to our glorious Master, the Lich King.",},
},
THINK = {
	default =nil,
["Gregarious Grell"] = { "wonders what it would be like to have a minion.", 
    },    
["Lil' K.T."] = {  "thinks about himself as well in his spare time.",},
["Lil' Ragnaros"] = {   "dreams about setting the world on fire."},
},
THIRSTY = {
	default = {
		"suggests a nice refreshing beer.",
        "suggests an ice cold can of redbull.",
	},
	cat = {
		"suggests a nice glass of milk.",
	},
	snake = {
		"suggests a nice glass of milk.",
	},
	["Warbot"] = {  "suggests a nice refreshing Mountain Dew.",
	},
	["Ethereal Soul-Trader"] = {  "grins and tells you, \"Of course you may have a drink, for the right price.\"", },	
	["Gregarious Grell"] = { "reminds you to squeeze Grell Moss for liquid.", 
    },
    ["Lil' K.T."] = {  "picked something up from Illidan. \"You are not prepared!\"",},
    ["Lil' Ragnaros"] = {   "suggests a flaming Homer."},
},
THREATEN = {
	default = {
		"cowers in fear.",
	},
	bird = {  "circles overhead, waiting for an opening to attack.", },
    ["Gregarious Grell"] = { "shouts, \"No master! %t has children!\"", 
    },
    ["Lil' Ragnaros"] = {   "come forth, my servants, defend your master!"},
	["Lil' K.T."] = {  "is now taunt immune!"},
},
TICKLE = {
	default = nil,
	beast = {  "rolls on its back gleefully.",
	 },
	evil = {  "is not ticklish.",},
    mech = {  "does not compute.",},
    ["Gregarious Grell"] = { "yells, \"No master! %t is ticklish!\"", 
    }
},
TIRED = {
	default = nil,
	beast = {  "jumps up and down like a bundle of energy.", },
	cat = {  "is already taking a cat nap.", },
    ["Gregarious Grell"] = { "jumps up and down like a a bundle of energy.", 
    },
    ["Lil' Ragnaros"] = {   "no, nooooo, this was to be my hour of triumph."},
	["Lil' K.T."] = {  "offers you immortality and a body that will never tire.",},
},
TRAIN = {
	default = nil,
  humanoid = {  "joins in, \"Choo, choo!\"", },
    ["Gregarious Grell"] = { "says, \"oohc, ooch.\"", 
    },
	["Lil' K.T."] = {  "complains, \"Enough, I grow tired of these distractions.\"",},
},
TRUCE = {
	default =nil,
    ["Lil' Ragnaros"] = {  "pathetic!"},
	["Lil' K.T."] = {  "threatens no quarter from the Scourge.",},

},
TWIDDLE = {
	default = nil,
  ["Lil' K.T."] = {  "straightens his robes.",},
},
Target = {
	default = {
		"says \"look, %t\".",
		"says \"There's %t\".",
		"says \"What is it I see? A %t!\"",
		"says \"Hey, that's %t.\"",
		"says \"I see %t.\"",
		"admires %t.",
		"is scared of %t.",
		"waves at %t.",
		"laughs at %t.",
		"giggles at %t.",
		"blushes at %t.",
		"winks at %t.",
		"hugs %t.",
		"runs away from %t.",
		"runs under %t's feet.",
		"loves %t.",
		"dislikes %t.",
		"says \"What is it I see? It's a %t\".",
		"thinks %t is cute.",
		"thinks %t should get a haircut.",
		"loves %t.",
		"likes %t's haircut.",
		"thinks %t is a sexy devil.",
		"reaches out and pokes %t in the arm.",
		"agrees with %t.",
		"is amazed by %t.",
		"raises a fist in anger at %t.",
		"apologizes to %t. Sorry!",
		"applauds at %t. Bravo!",
		"tells everyone to attack %t.",
		"barks at %t",
		"is so bashful...too bashful to get %t's attention.",
		"beckons %t over.",
		"begs %t. How pathetic.",
		"burps rudely in %t's face.",
		"bites %t. Ouch!",
		"blinks at %t.",
		"blows a kiss to %t.",
		"blushes at %t.",
		"boggles at %t.",
		"bonks %t on the noggin. Doh!",
		"is terribly bored with %t.",
		"bounces up and down in front of %t.",
		"bows before %t.",
		"applauds at %t. Bravo!",
		"let's %t know you'll be right back.",
		"burps rudely in %t's face.",
		"waves goodbye to %t. Farewell!",
		"cackles maniacally at %t.",
		"tries to calm %t down.",
		"scratch %t. How catty!",
		"cheers at %t.",
		"begins to eat in front of %t.",
		"chuckles at %t.",
		"claps excitedly for %t.",
		"lets %t know that you are cold.",
		"comforts %t.",
		"commends %t on a job well done.",
		"looks at %t with a confused look.",
		"congratulates %t.",
		"coughs at %t.",
		"cowers in fear at the sight of %t.",
		"cracks your knuckles while staring at %t.",
		"cringes away from %t.",
		"cries on %t's shoulder.",
		"cuddles up against %t.",
		"is curious what %t is up to.",
		"curtseys before %t.",
		"dances with %t.",
		"frowns with disappointment at %t.",
		"bonks %t on the noggin. Doh!",
		"threatens %t with the wrath of doom.",
		"raises a drink to %t. Cheers!",
		"looks at %t and begin to drool.",
		"ducks behind %t.",
		"begins to eat in front of %t.",
		"talks excitedly with %t.",
		"eyes %t up and down.",
		"looks over at %t and cover your face with your palm.",
		"waves goodbye to %t. Farewell!",
		"brushes up against %t and fart loudly.",
		"cowers in fear at the sight of %t.",
		"begins to eat in front of %t.",
		"fidgets impatiently while waiting for %t.",
		"yells for %t to flee!",
		"flexes at %t. Oooooh so strong!",
		"flirts with %t.",
		"flops about helplessly around %t.",
		"motions for %t to follow.",
		"is hungry. Maybe %t has some food...",
		"frowns with disappointment at %t.",
		"gasps at %t.",
		"gazes eagerly at %t.",
		"giggles at %t.",
		"is very happy with %t!",
		"glares angrily at %t.",
		"gloats over %t's misfortune.",
		"claps for %t, clearly unimpressed.",
		"waves goodbye to %t. Farewell!",
		"greets %t warmly.",
		"grins wickedly at %t.",
		"looks at %t and groan.",
		"grovels before %t like a subservient peon.",
		"growls menacingly at %t.",
		"takes one look at %t and let out a guffaw!",
		"hails %t.",
		"is very happy with %t!",
		"greets %t with a hearty hello!",
		"greets %t with a hearty hello!",
		"gives %t a high five!",
		"hugs %t.",
		"is hungry. Maybe %t has some food...",
		"fidgets impatiently while waiting for %t.",
		"points out %t as an incoming enemy!",
		"thinks %t is the son of a motherless ogre.",
		"introduces itself to %t.",
		"lets %t know that you were just kidding!",
		"blows a kiss to %t.",
		"kneels before %t.",
		"cracks your knuckles while staring at %t.",
		"laughs at %t.",
		"lavishes praise upon %t.",
		"lies down before %t.",
		"licks %t.",
		"lies down before %t.",
		"listens intently to %t.",
		"laughs at %t.",
		"wants %t to know that you are hopelessly lost.",
		"loves %t.",
		"raises your fist in anger at %t.",
		"massages %t's shoulders.",
		"moans suggestively at %t.",
		"mocks the foolishness of %t.",
		"moos at %t. Mooooooooooo.",
		"drops your trousers and moon %t.",
		"tells %t NO. Not going to happen.",
		"nods at %t.",
		"picks your nose and show it to %t.",
		"takes one look at %t and panic.",
		"raises a drink to %t. Cheers!",
		"gently pat %t.",
		"peers at %t searchingly.",
		"grovels before %t like a subservient peon.",
		"shoos %t away. Be gone pest!",
		"picks your nose and show it to %t.",
		"looks down upon %t with pity.",
		"is hungry. Maybe %t has some food...",
		"pleads with %t.",
		"points at %t.",
		"pokes %t. Hey!",
		"ponders %t's actions.",
		"pounces on top of %t.",
		"lavishes praise upon %t.",
		"says a prayer for %t.",
		"purrs at %t.",
		"is puzzled by %t.",
		"questions %t.",
		"looks at %t and raises your hand.",
		"makes a rude gesture at %t.",
		"lets %t know that you are ready!",
		"shakes your rear at %t.",
		"roars with bestial vigor at %t. So fierce!",
		"rolls on the floor laughing at %t.",
		"makes a rude gesture at %t.",
		"salutes %t with respect.",
		"is scared of %t.",
		"scratches %t. How catty!",
		"thinks %t is a sexy devil.",
		"shakes your rear at %t.",
		"shimmy’s before %t.",
		"raises a drink to %t. Cheers!",
		"shivers beside %t. Chilling!",
		"shoos %t away. Be gone pest!",
		"shrugs at %t. Who knows?",
		"smiles shyly at %t.",
		"sighs at %t.",
		"tells %t a joke.",
		"slaps %t across the face. Ouch!",
		"falls asleep. Zzzzzzz.",
		"smells %t. Wow, someone stinks!",
		"smiles at %t.",
		"smirks slyly at %t.",
		"bares your teeth and snarl at %t.",
		"snickers at %t.",
		"sniffs %t.",
		"snubs %t.",
		"cries on %t's shoulder.",
		"soothes %t. There, there...things will be ok.",
		"apologizes to %t. Sorry!",
		"spits on %t.",
		"cuddles up against %t.",
		"stares %t down.",
		"smells %t. Wow, someone stinks!",
		"flexes at %t. Oooooh so strong!",
		"struts around %t. Cluck, Cluck, Chicken!",
		"is surprised by %t's actions.",
		"surrenders before %t. Such is the agony of defeat...",
		"wants to talk things over with %t",
		"talks excitedly with %t",
		"questions %t.",
		"taps its foot as you wait for %t.",
		"makes a taunting gesture at %t. Bring it!",
		"teases %t.",
		"thanks %t.",
		"lets %t know you are thirsty. Spare a drink?",
		"threatens %t with the wrath of doom.",
		"tickles %t. Hee hee!",
		"lets %t know that you are tired.",
		"thanks %t.",
		"votes %t's motion.",
		"basks in the glory of victory with %t.",
		"plays the world's smallest violin for %t.",
		"looks at %t and raise your hand.",
		"asks %t to wait.",
		"waves at %t.",
		"cries on %t's shoulder.",
		"welcomes %t.",
		"whines pathetically at %t.",
		"whistles at %t.",
		"grins wickedly at %t.",
		"winks slyly at %t.",
		"cheers at %t.",
		"works with %t.",
		"threatens %t with the wrath of doom.",
		"yawns sleepily at %t.",
		"is very happy with %t!",
		"nods at %t.",
		"was happy to help %t. ",
	},
	cat = {
		"purrs at %t.",
		"wraps itself around %t leg.",
		"paws at %t.",
		"looks at %t for some food.",
	},
	snake = {
		"hisses at %t.",
		"wraps itself around %t leg.",
		"hisses at %t.",
		"looks at %t for some food.",
	},
},
VETO = {
	default = nil,
  ["Lil' K.T."] = {  "will see what the Lich King thinks of this.",},
},
VICTORY = {
	default = nil,
  ["Gregarious Grell"] = { "shouts, \"%t did good! %t did good!", 
    },
  ["Lil' Ragnaros"] = {  "die insect!"},
  ["Lil' K.T."] = {  "grins and says, \"All part of the Master's plan.\"",},
},
VIOLIN = {
	default =nil,
	humanoid = {  "cries.", },
	["Ethereal Soul-Trader"] = {  "asks, \"Is that one of a kind? Care to barter?\"", 
	},					
	["Lil' K.T."] = { "claps for you, clearly unimpressed.",},
},
WAIT = {
	default = {
		"waits.",
	},
  ["Lil' K.T."] = {  "waits, but doesn't seem happy about it.",},
},
WARN = {
	default =nil,
},
WAVE = {
	default = {
		"waves back.",
	},
	cat = {
		"snuggles your leg.",
		"purrs.",
	},
	snake = {
		"hisses.",
		"hisses.",
	},
  ["Lil' K.T."] = {  "mocks your foolishness.",},
},
WELCOME = {
	default = {
		"waves back.",
	},
	cat = {
		"purrs.",
	},
	snake = {
		"hisses.",
	},
  ["Lil' K.T."] = {  "floats intimidatingly and doesn't reciprocate.",},
},
WHINE = {
	default = nil,
evil = {  "is not here to babysit you.", },
},
WHISTLE = {
	default =nil,
  ["Lil' K.T."] = {  "was rated Hottest Lich of 2009.",},
},
WINK = {
	default =nil,
},
WORK = {
	default = {
		"appreciates the help.",
	},
	evil = {  "laughs diabolically. Now its evil plans will be set in motion quicker.",
	},	
	inanimate = {  "works with you, synergy!", },					 
	["Lil' K.T."] = {  "reminds you that you work for him, not with him.",},
},
YAWN = {
	default =nil,
},

}

-- Thanks to pet plus for the category's!
-- bat, beast, bird, cat, crab, croc, dino, dragon, dragonhawk, elephant, elemental, evil, flying insect, frog,
--  humanoid, inanimate, insect, mech, murloc, ooze, plant, rabbit, snake, 
CritterEmote_Personalities = {
        ["Albino Snake"] = "snake",
        ["Alliance Balloon"] = "inanimate",
        ["Ammen Vale Lashling"] = "plant",
        ["Ancona Chicken"] = "bird",
        ["Argent Gruntling"] = "humanoid",
        ["Argent Squire"] = "humanoid", 
        ["Armadillo Pup"] = "beast",
        ["Azure Whelpling"] = "dragon",
        ["Baby Blizzard Bear"] = "beast",
        ["Bananas"] = "beast",
        ["Black Kingsnake"] = "snake",
        ["Black Tabby Cat"] = "cat",
        ["Blue Clockwork Rocket Bot"] = "mech",
        ["Blue Dragonhawk Hatchling"] = "dragonhawk",
        ["Blue Mini Jouster"]  = "bird",
        ["Blue Moth"] = "flying insect",
        ["Bombay Cat"] = "cat",
        ["Brilliant Kaliri"] = "bird",
        ["Brown Prairie Dog"] = "beast",
        ["Brown Rabbit"] = "rabbit",
        ["Brown Snake"] = "snake",
        ["Calico Cat"] = "cat",
        ["Celestial Dragon"] = "dragon",
        ["Cenarion Hatchling"] = "bird",
        ["Chuck"] = "croc",
        ["Clockwork Gnome"] = "mech",
        ["Clockwork Rocket Bot"] = "mech",
        ["Cobra Hatchling"] = "snake",
        ["Cockatiel"] = "bird",
        ["Cockroach"] = "flying insect",
        ["Core Hound Pup"] = "beast",
        ["Cornish Rex Cat"] = "cat",
        ["Crawling Claw"] = "inanimate",
        ["Creepy Crate"] = "inanimate",
        ["Crimson Lasher"] = "plant",
        ["Crimson Snake"] = "snake",
        ["Crimson Whelpling"] = "dragon",
        ["Curious Oracle Hatchling"] = "humanoid",
        ["Curious Wolvar Pup"] = "humanoid",
        ["Dark Phoenix Hatchling"] = "bird",
        ["Dark Whelpling"] = "dragon",
        ["Darkmoon Balloon"] = "inanimate",
        ["Darkmoon Cub"] = "beast",
        ["Darkmoon Monkey"] = "beast",
        ["Darkmoon Tonk"] = "inanimate",
        ["Darkmoon Turtle"] = "beast",
        ["Darkmoon Zeppelin"] = "inanimate",
        ["Darting Hatchling"] = "dino",
        ["De-Weaponized Mechanical Companion"] = "mech",
        ["Deathy"] = "murloc",
        ["Deviate Hatchling"] = "dino",
        ["Disgusting Oozeling"] = "ooze",
        ["Dragon Kite"] = "inanimate",
        ["Dun Morogh Cub"] = "beast",
        ["Durotar Scorpion"] = "insect",
        ["Egbert"] = "bird",
        ["Elementium Geode"] = "inanimate",
        ["Elwynn Lamb"] = "beast",
        ["Emerald Whelpling"] = "dragon",
        ["Enchanted Broom"] = "inanimate",
        ["Enchanted Lantern"] = "inanimate",
        ["Essence of Competition"] = "dragon",
        ["Ethereal Soul-Trader"] = "humanoid",
        ["Father Winter's Helper"] = "humanoid",
        ["Feline Familiar"] = "cat",
        ["Festival Lantern"] = "inanimate",
        ["Firefly"] = "flying insect",
        ["Fossilized Hatchling"] = "dino",
        ["Fox Kit"] = "beast",
        ["Frigid Frostling"] = "elemental",
        ["Frosty"] = "dragon",
        ["Ghostly Skull"] = "evil",
        ["Giant Sewer Rat"] = "beast",
        ["Gold Mini Jouster"] = "bird",
        ["Golden Dragonhawk Hatchling"] = "dragonhawk",
        ["Golden Pig"] = "beast",
        ["Great Horned Owl"] = "bird",
        ["Green Wing Macaw"] = "bird",
        ["Gregarious Grell"] = "evil",
        ["Grunty"] = "murloc",
        ["Gryphon Hatchling"] = "bird",
        ["Guardian Cub"] = "beast",
        ["Guild Herald"] = "humanoid",
        ["Guild Page"] = "humanoid",
        ["Gundrak Hatchling"] = "dino",
        ["Gurky"] = "murloc",
        ["Hawk Owl"] = "bird",
        ["Hippogryph Hatchling"] = "bird",
        ["Horde Balloon"] = "inanimate",
        ["Hyacinth Macaw"] = "bird",
        ["Hyjal Bear Cub"] = "beast",
        ["Jade Tiger"] = "beast",
        ["Jubling"] = "frog",
        ["Kirin Tor Familiar"] = "humanoid",
        ["Landro's Lichling"] = "evil",
        ["Landro's Lil' XT"] = "mech",
        ["Lashtail Hatchling"] = "dino",
        ["Leaping Hatchling"] = "dino",
        ["Legs"] = "beast",
        ["Lifelike Toad"] = "mech", 
        ["Lil' Deathwing"] = "dragon",
        ["Lil' K.T."] = "evil",
        ["Lil' Ragnaros"] = "evil",
        ["Lil' Smokey"] = "mech",
        ["Lil' Tarecgosa"] = "dragon",
        ["Lil' XT"] = "mech",
        ["Little Fawn"] = "beast",
        ["Lucky"] = "beast",
        ["Lumpy"] = "elemental",
        ["Lunar Lantern"] = "inanimate",
        ["Lurky"] = "murloc",
        ["Magic Lamp"] = "inanimate",
        ["Magical Crawdad"] = "crab",
        ["Mana Wyrmling"] = "beast",
        ["Mechanical Chicken"] = "mech",
        ["Mechanical Squirrel"] = "mech",
        ["Mechanopeep"] = "mech",       
        ["Mini Diablo"] = "evil",
        ["Mini Tyrael"] = "humanoid",   
        ["Mini Thor"] = "mech",
        ["Miniwing"] = "bird",
        ["Mojo"] = "frog",
        ["Moonkin Hatchling"] = "humanoid",
        ["Mr. Chilly"] = "beast",
        ["Mr. Grubbs"] = "beast",
        ["Mr. Wiggles"] = "beast",
        ["Muckbreath"] = "croc",
        ["Mulgore Hatchling"] = "bird",
        ["Murky"] = "Murloc",
        ["Murkimus the Gladiator"] = "murloc",
        ["Murky"] = "murloc",
        ["Nether Ray Fry"] = "beast",
        ["Netherwhelp"] = "dragon",
        ["Nightsaber Cub"] = "beast",
        ["Nuts"] = "beast",
        ["Obsidian Hatchling"] = "dino",
        ["Onyx Panther"] = "beast",
        ["Onyxian Whelpling"] = "dragon",
        ["Orange Tabby Cat"] = "cat",
        ["Panda Cub"] = "beast",
        ["Pandaren Monk"] = "humanoid",
        ["Panther Cub"] = "beast",
        ["Peanut"] = "elephant",
        ["Pebble"] = "elemental",
        ["Peddlefeet"] = "humanoid",
        ["Pengu"] = "beast",
        ["Perky Pug"] = "beast",
        ["Personal World Destroyer"] = "mech",
        ["Pet Bombling"] = "mech",
        ["Phoenix Hatchling"] = "bird",
        ["Pint-Sized Pink Pachyderm"] = "elephant",
        ["Plump Turkey"] = "bird",
        ["Poley"] = "beast",
        ["Proto-Drake Whelp"] = "dragon",
        ["Pterrodax Hatchling"] = "dino",
        ["Purple Puffer"] = "inanimate",
        ["Purple Jade Leopard"] = "beast",
        ["Ravasaur Hatchling"] = "dino",
        ["Razormaw Hatchling"] = "dino",
        ["Razzashi Hatchling"] = "dino",
        ["Red Dragonhawk Hatchling"] = "dragonhawk",
        ["Red Moth"] = "flying insect",
        ["Rocket Chicken"] = "mech",
        ["Rustberg Seagull"] = "bird",
        ["Scooter The Snail"] = "beast",
        ["Sea Pony"] = "inanimate",
        ["Searing Scorchling"] = "elemental",
        ["Sen'jin Fetish"] = "inanimate",
        ["Senegal"] = "bird",
        ["Shimmering Wyrmling"] = "beast",
        ["Siamese Cat"] = "cat",
        ["Silver Dragonhawk Hatchling"] = "dragonhawk",
        ["Silver Pig"] = "beast",
        ["Silver Tabby Cat"] = "cat",
        ["Singing Sunflower"] = "plant",
        ["Sinister Squashling"] = "evil",
        ["Smolderweb Hatchling"] = "insect",
        ["Snarly"] = "croc",
        ["Snowshoe Rabbit"] = "rabbit",
        ["Soul Of The Aspects"] = "dragon",
        ["Spectral Tiger Cub"] = "cat",
        ["Speedy"] = "beast",
        ["Spirit of Competition"] = "dragon",
        ["Spirit of Summer"] = "elemental",
        ["Spring Rabbit"] = "rabbit",
        ["Sprite Darter Hatchling"] = "dragon",
        ["Stinker"] = "beast",
        ["Strand Crawler"] = "crab",
        ["Teldrassil Sproutling"] = "plant",
        ["Tickbird Hatchling"] = "bird",
        ["Tiny Green Dragon"] = "dragon",
        ["Tiny Red Dragon"] = "dragon",
        ["Tiny Shale Spider"] = "beast",
        ["Tiny Snowman"] = "humanoid",
        ["Tiny Sporebat"] = "beast",
        ["Tirisfal Batling"] = "bat",
        ["Toothy"] = "croc",    
        ["Toxic Wasteling"] = "ooze",
        ["Tranquil Mechanical Yeti"] = "mech",
        ["Tree Frog"] = "frog",
        ["Tuskarr Kite"] = "inanimate",
        ["Vampiric Batling"] = "bat",
        ["Voodoo Figurine"] = "humanoid",
        ["Warbot"] = "mech",
        ["Westfall Chicken"] = "bird",
        ["Whiskers the Rat"] = "beast", 
        ["White Kitten"] = "cat",
        ["White Moth"] = "flying insect",
        ["White Tickbird Hatchling"] = "bird",
        ["Willy"] = "evil",
        ["Wind Rider Cub"] = "beast",
        ["Winter Reindeer"] = "beast",
        ["Winter's Little Helper"] = "humanoid",
        ["Winterspring Cub"] = "beast",
        ["Withers"] = "plant",
        ["Wolpertinger"] = "beast",
        ["Wood Frog"] = "frog",
        ["Worg Pup"] = "beast",
        ["Yellow Moth"] = "flying insect",
        ["Zergling"] = "evil",
        ["Zipao Tiger"] = "beast",
}


